/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
/**
 *
 * @export
 * @interface CancelMeeting200ResponseMeeting
 */
export interface CancelMeeting200ResponseMeeting {
  /**
   *
   * @type {string}
   * @memberof CancelMeeting200ResponseMeeting
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof CancelMeeting200ResponseMeeting
   */
  status?: CancelMeeting200ResponseMeetingStatusEnum
}

/**
 * @export
 * @enum {string}
 */
export enum CancelMeeting200ResponseMeetingStatusEnum {
  Cancelled = "Cancelled",
}

/**
 * Check if a given object implements the CancelMeeting200ResponseMeeting interface.
 */
export function instanceOfCancelMeeting200ResponseMeeting(
  value: object,
): boolean {
  let isInstance = true

  return isInstance
}

export function CancelMeeting200ResponseMeetingFromJSON(
  json: any,
): CancelMeeting200ResponseMeeting {
  return CancelMeeting200ResponseMeetingFromJSONTyped(json, false)
}

export function CancelMeeting200ResponseMeetingFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CancelMeeting200ResponseMeeting {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    status: !exists(json, "status") ? undefined : json["status"],
  }
}

export function CancelMeeting200ResponseMeetingToJSON(
  value?: CancelMeeting200ResponseMeeting | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id,
    status: value.status,
  }
}
