/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
import type { GetWorkflows200ResponseInnerDefinition } from "./GetWorkflows200ResponseInnerDefinition"
import {
  GetWorkflows200ResponseInnerDefinitionFromJSON,
  GetWorkflows200ResponseInnerDefinitionFromJSONTyped,
  GetWorkflows200ResponseInnerDefinitionToJSON,
} from "./GetWorkflows200ResponseInnerDefinition"

/**
 *
 * @export
 * @interface CreateWorkflow200Response
 */
export interface CreateWorkflow200Response {
  /**
   *
   * @type {string}
   * @memberof CreateWorkflow200Response
   */
  id: string
  /**
   *
   * @type {Date}
   * @memberof CreateWorkflow200Response
   */
  updatedAt: Date
  /**
   *
   * @type {Date}
   * @memberof CreateWorkflow200Response
   */
  createdAt?: Date
  /**
   *
   * @type {string}
   * @memberof CreateWorkflow200Response
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof CreateWorkflow200Response
   */
  description: string
  /**
   *
   * @type {string}
   * @memberof CreateWorkflow200Response
   */
  workspaceId: string
  /**
   *
   * @type {string}
   * @memberof CreateWorkflow200Response
   */
  triggerType?: CreateWorkflow200ResponseTriggerTypeEnum
  /**
   *
   * @type {string}
   * @memberof CreateWorkflow200Response
   */
  status: CreateWorkflow200ResponseStatusEnum
  /**
   *
   * @type {GetWorkflows200ResponseInnerDefinition}
   * @memberof CreateWorkflow200Response
   */
  definition: GetWorkflows200ResponseInnerDefinition
}

/**
 * @export
 * @enum {string}
 */
export enum CreateWorkflow200ResponseTriggerTypeEnum {
  ApplicationCreated = "ApplicationCreated",
}
/**
 * @export
 * @enum {string}
 */
export enum CreateWorkflow200ResponseStatusEnum {
  Draft = "Draft",
  Active = "Active",
  Archived = "Archived",
}

/**
 * Check if a given object implements the CreateWorkflow200Response interface.
 */
export function instanceOfCreateWorkflow200Response(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && "id" in value
  isInstance = isInstance && "updatedAt" in value
  isInstance = isInstance && "name" in value
  isInstance = isInstance && "description" in value
  isInstance = isInstance && "workspaceId" in value
  isInstance = isInstance && "status" in value
  isInstance = isInstance && "definition" in value

  return isInstance
}

export function CreateWorkflow200ResponseFromJSON(
  json: any,
): CreateWorkflow200Response {
  return CreateWorkflow200ResponseFromJSONTyped(json, false)
}

export function CreateWorkflow200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateWorkflow200Response {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: json["id"],
    updatedAt: new Date(json["updatedAt"]),
    createdAt: !exists(json, "createdAt")
      ? undefined
      : new Date(json["createdAt"]),
    name: json["name"],
    description: json["description"],
    workspaceId: json["workspaceId"],
    triggerType: !exists(json, "triggerType") ? undefined : json["triggerType"],
    status: json["status"],
    definition: GetWorkflows200ResponseInnerDefinitionFromJSON(
      json["definition"],
    ),
  }
}

export function CreateWorkflow200ResponseToJSON(
  value?: CreateWorkflow200Response | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id,
    updatedAt: value.updatedAt.toISOString(),
    createdAt:
      value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
    name: value.name,
    description: value.description,
    workspaceId: value.workspaceId,
    triggerType: value.triggerType,
    status: value.status,
    definition: GetWorkflows200ResponseInnerDefinitionToJSON(value.definition),
  }
}
