/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAttributeRequestConfigurationAnyOf1
 */
export interface CreateAttributeRequestConfigurationAnyOf1 {
    /**
     * 
     * @type {string}
     * @memberof CreateAttributeRequestConfigurationAnyOf1
     */
    type?: CreateAttributeRequestConfigurationAnyOf1TypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateAttributeRequestConfigurationAnyOf1
     */
    dateFormat: CreateAttributeRequestConfigurationAnyOf1DateFormatEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateAttributeRequestConfigurationAnyOf1
     */
    timeFormat: CreateAttributeRequestConfigurationAnyOf1TimeFormatEnum;
}

/**
* @export
* @enum {string}
*/
export enum CreateAttributeRequestConfigurationAnyOf1TypeEnum {
    Date = 'Date'
}
/**
* @export
* @enum {string}
*/
export enum CreateAttributeRequestConfigurationAnyOf1DateFormatEnum {
    FullDate = 'Full date',
    MonthDayYear = 'Month/Day/Year',
    DayMonthYear = 'Day/Month/Year',
    YearMonthDay = 'Year/Month/Day',
    Relative = 'Relative'
}
/**
* @export
* @enum {string}
*/
export enum CreateAttributeRequestConfigurationAnyOf1TimeFormatEnum {
    Hidden = 'Hidden',
    _12Hour = '12 hour',
    _24Hour = '24 hour'
}


/**
 * Check if a given object implements the CreateAttributeRequestConfigurationAnyOf1 interface.
 */
export function instanceOfCreateAttributeRequestConfigurationAnyOf1(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "dateFormat" in value;
    isInstance = isInstance && "timeFormat" in value;

    return isInstance;
}

export function CreateAttributeRequestConfigurationAnyOf1FromJSON(json: any): CreateAttributeRequestConfigurationAnyOf1 {
    return CreateAttributeRequestConfigurationAnyOf1FromJSONTyped(json, false);
}

export function CreateAttributeRequestConfigurationAnyOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAttributeRequestConfigurationAnyOf1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'dateFormat': json['dateFormat'],
        'timeFormat': json['timeFormat'],
    };
}

export function CreateAttributeRequestConfigurationAnyOf1ToJSON(value?: CreateAttributeRequestConfigurationAnyOf1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'dateFormat': value.dateFormat,
        'timeFormat': value.timeFormat,
    };
}

