/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
import type { GetMeetingNotes200ResponseMeetingNotesInner } from "./GetMeetingNotes200ResponseMeetingNotesInner"
import {
  GetMeetingNotes200ResponseMeetingNotesInnerFromJSON,
  GetMeetingNotes200ResponseMeetingNotesInnerFromJSONTyped,
  GetMeetingNotes200ResponseMeetingNotesInnerToJSON,
} from "./GetMeetingNotes200ResponseMeetingNotesInner"

/**
 *
 * @export
 * @interface CreateMeetingNote201Response
 */
export interface CreateMeetingNote201Response {
  /**
   *
   * @type {GetMeetingNotes200ResponseMeetingNotesInner}
   * @memberof CreateMeetingNote201Response
   */
  meetingNote?: GetMeetingNotes200ResponseMeetingNotesInner
}

/**
 * Check if a given object implements the CreateMeetingNote201Response interface.
 */
export function instanceOfCreateMeetingNote201Response(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function CreateMeetingNote201ResponseFromJSON(
  json: any,
): CreateMeetingNote201Response {
  return CreateMeetingNote201ResponseFromJSONTyped(json, false)
}

export function CreateMeetingNote201ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateMeetingNote201Response {
  if (json === undefined || json === null) {
    return json
  }
  return {
    meetingNote: !exists(json, "meetingNote")
      ? undefined
      : GetMeetingNotes200ResponseMeetingNotesInnerFromJSON(
          json["meetingNote"],
        ),
  }
}

export function CreateMeetingNote201ResponseToJSON(
  value?: CreateMeetingNote201Response | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    meetingNote: GetMeetingNotes200ResponseMeetingNotesInnerToJSON(
      value.meetingNote,
    ),
  }
}
