/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateFormRequestFieldsInnerAttributeLinked } from './CreateFormRequestFieldsInnerAttributeLinked';
import {
    CreateFormRequestFieldsInnerAttributeLinkedFromJSON,
    CreateFormRequestFieldsInnerAttributeLinkedFromJSONTyped,
    CreateFormRequestFieldsInnerAttributeLinkedToJSON,
} from './CreateFormRequestFieldsInnerAttributeLinked';
import type { CreateFormRequestFieldsInnerMaxSelection } from './CreateFormRequestFieldsInnerMaxSelection';
import {
    CreateFormRequestFieldsInnerMaxSelectionFromJSON,
    CreateFormRequestFieldsInnerMaxSelectionFromJSONTyped,
    CreateFormRequestFieldsInnerMaxSelectionToJSON,
} from './CreateFormRequestFieldsInnerMaxSelection';

/**
 * 
 * @export
 * @interface CreateFormRequestFieldsInner
 */
export interface CreateFormRequestFieldsInner {
    /**
     * 
     * @type {boolean}
     * @memberof CreateFormRequestFieldsInner
     */
    required: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateFormRequestFieldsInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFormRequestFieldsInner
     */
    id: string;
    /**
     * 
     * @type {CreateFormRequestFieldsInnerAttributeLinked}
     * @memberof CreateFormRequestFieldsInner
     */
    attributeLinked?: CreateFormRequestFieldsInnerAttributeLinked;
    /**
     * 
     * @type {string}
     * @memberof CreateFormRequestFieldsInner
     */
    type?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateFormRequestFieldsInner
     */
    options?: Array<string>;
    /**
     * 
     * @type {CreateFormRequestFieldsInnerMaxSelection}
     * @memberof CreateFormRequestFieldsInner
     */
    maxSelection?: CreateFormRequestFieldsInnerMaxSelection;
    /**
     * 
     * @type {boolean}
     * @memberof CreateFormRequestFieldsInner
     */
    includeTime?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CreateFormRequestFieldsInner
     */
    enableEndDate?: boolean;
}

/**
 * Check if a given object implements the CreateFormRequestFieldsInner interface.
 */
export function instanceOfCreateFormRequestFieldsInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "required" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function CreateFormRequestFieldsInnerFromJSON(json: any): CreateFormRequestFieldsInner {
    return CreateFormRequestFieldsInnerFromJSONTyped(json, false);
}

export function CreateFormRequestFieldsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFormRequestFieldsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'required': json['required'],
        'name': json['name'],
        'id': json['id'],
        'attributeLinked': !exists(json, 'attributeLinked') ? undefined : CreateFormRequestFieldsInnerAttributeLinkedFromJSON(json['attributeLinked']),
        'type': !exists(json, 'type') ? undefined : json['type'],
        'options': !exists(json, 'options') ? undefined : json['options'],
        'maxSelection': !exists(json, 'maxSelection') ? undefined : CreateFormRequestFieldsInnerMaxSelectionFromJSON(json['maxSelection']),
        'includeTime': !exists(json, 'includeTime') ? undefined : json['includeTime'],
        'enableEndDate': !exists(json, 'enableEndDate') ? undefined : json['enableEndDate'],
    };
}

export function CreateFormRequestFieldsInnerToJSON(value?: CreateFormRequestFieldsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'required': value.required,
        'name': value.name,
        'id': value.id,
        'attributeLinked': CreateFormRequestFieldsInnerAttributeLinkedToJSON(value.attributeLinked),
        'type': value.type,
        'options': value.options,
        'maxSelection': CreateFormRequestFieldsInnerMaxSelectionToJSON(value.maxSelection),
        'includeTime': value.includeTime,
        'enableEndDate': value.enableEndDate,
    };
}

