/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
/**
 *
 * @export
 * @interface CreateAnApplicationRequest
 */
export interface CreateAnApplicationRequest {
  /**
   * The ID of the opening to apply for
   * @type {string}
   * @memberof CreateAnApplicationRequest
   */
  openingId: string
  /**
   * Candidate's email address
   * @type {string}
   * @memberof CreateAnApplicationRequest
   */
  email: string
  /**
   * Candidate's first name
   * @type {string}
   * @memberof CreateAnApplicationRequest
   */
  firstName: string
  /**
   * Candidate's last name
   * @type {string}
   * @memberof CreateAnApplicationRequest
   */
  lastName: string
  /**
   * Application responses/answers to form questions
   * @type {{ [key: string]: any; }}
   * @memberof CreateAnApplicationRequest
   */
  responses?: { [key: string]: any }
}

/**
 * Check if a given object implements the CreateAnApplicationRequest interface.
 */
export function instanceOfCreateAnApplicationRequest(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && "openingId" in value
  isInstance = isInstance && "email" in value
  isInstance = isInstance && "firstName" in value
  isInstance = isInstance && "lastName" in value

  return isInstance
}

export function CreateAnApplicationRequestFromJSON(
  json: any,
): CreateAnApplicationRequest {
  return CreateAnApplicationRequestFromJSONTyped(json, false)
}

export function CreateAnApplicationRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateAnApplicationRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    openingId: json["openingId"],
    email: json["email"],
    firstName: json["firstName"],
    lastName: json["lastName"],
    responses: !exists(json, "responses") ? undefined : json["responses"],
  }
}

export function CreateAnApplicationRequestToJSON(
  value?: CreateAnApplicationRequest | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    openingId: value.openingId,
    email: value.email,
    firstName: value.firstName,
    lastName: value.lastName,
    responses: value.responses,
  }
}
