/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateEmailAddress200Response
 */
export interface CreateEmailAddress200Response {
    /**
     * 
     * @type {string}
     * @memberof CreateEmailAddress200Response
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof CreateEmailAddress200Response
     */
    updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreateEmailAddress200Response
     */
    createdAt: Date;
    /**
     * 
     * @type {any}
     * @memberof CreateEmailAddress200Response
     */
    deletedAt?: any | null;
    /**
     * 
     * @type {string}
     * @memberof CreateEmailAddress200Response
     */
    workspaceId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEmailAddress200Response
     */
    profileId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEmailAddress200Response
     */
    email: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateEmailAddress200Response
     */
    isActive?: boolean;
}

/**
 * Check if a given object implements the CreateEmailAddress200Response interface.
 */
export function instanceOfCreateEmailAddress200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "updatedAt" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "workspaceId" in value;
    isInstance = isInstance && "profileId" in value;
    isInstance = isInstance && "email" in value;

    return isInstance;
}

export function CreateEmailAddress200ResponseFromJSON(json: any): CreateEmailAddress200Response {
    return CreateEmailAddress200ResponseFromJSONTyped(json, false);
}

export function CreateEmailAddress200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEmailAddress200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'updatedAt': (new Date(json['updatedAt'])),
        'createdAt': (new Date(json['createdAt'])),
        'deletedAt': !exists(json, 'deletedAt') ? undefined : json['deletedAt'],
        'workspaceId': json['workspaceId'],
        'profileId': json['profileId'],
        'email': json['email'],
        'isActive': !exists(json, 'isActive') ? undefined : json['isActive'],
    };
}

export function CreateEmailAddress200ResponseToJSON(value?: CreateEmailAddress200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'updatedAt': (value.updatedAt.toISOString()),
        'createdAt': (value.createdAt.toISOString()),
        'deletedAt': value.deletedAt,
        'workspaceId': value.workspaceId,
        'profileId': value.profileId,
        'email': value.email,
        'isActive': value.isActive,
    };
}

