/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
/**
 *
 * @export
 * @interface CreateEmailTemplateRequestContent
 */
export interface CreateEmailTemplateRequestContent {
  /**
   *
   * @type {string}
   * @memberof CreateEmailTemplateRequestContent
   */
  html: string
  /**
   *
   * @type {object}
   * @memberof CreateEmailTemplateRequestContent
   */
  json: object
}

/**
 * Check if a given object implements the CreateEmailTemplateRequestContent interface.
 */
export function instanceOfCreateEmailTemplateRequestContent(
  value: object,
): boolean {
  let isInstance = true
  isInstance = isInstance && "html" in value
  isInstance = isInstance && "json" in value

  return isInstance
}

export function CreateEmailTemplateRequestContentFromJSON(
  json: any,
): CreateEmailTemplateRequestContent {
  return CreateEmailTemplateRequestContentFromJSONTyped(json, false)
}

export function CreateEmailTemplateRequestContentFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateEmailTemplateRequestContent {
  if (json === undefined || json === null) {
    return json
  }
  return {
    html: json["html"],
    json: json["json"],
  }
}

export function CreateEmailTemplateRequestContentToJSON(
  value?: CreateEmailTemplateRequestContent | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    html: value.html,
    json: value.json,
  }
}
