/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
import type { CreateAnApplication201ResponseData } from "./CreateAnApplication201ResponseData"
import {
  CreateAnApplication201ResponseDataFromJSON,
  CreateAnApplication201ResponseDataFromJSONTyped,
  CreateAnApplication201ResponseDataToJSON,
} from "./CreateAnApplication201ResponseData"

/**
 *
 * @export
 * @interface CreateAnApplication201Response
 */
export interface CreateAnApplication201Response {
  /**
   *
   * @type {CreateAnApplication201ResponseData}
   * @memberof CreateAnApplication201Response
   */
  data?: CreateAnApplication201ResponseData
}

/**
 * Check if a given object implements the CreateAnApplication201Response interface.
 */
export function instanceOfCreateAnApplication201Response(
  value: object,
): boolean {
  let isInstance = true

  return isInstance
}

export function CreateAnApplication201ResponseFromJSON(
  json: any,
): CreateAnApplication201Response {
  return CreateAnApplication201ResponseFromJSONTyped(json, false)
}

export function CreateAnApplication201ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateAnApplication201Response {
  if (json === undefined || json === null) {
    return json
  }
  return {
    data: !exists(json, "data")
      ? undefined
      : CreateAnApplication201ResponseDataFromJSON(json["data"]),
  }
}

export function CreateAnApplication201ResponseToJSON(
  value?: CreateAnApplication201Response | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    data: CreateAnApplication201ResponseDataToJSON(value.data),
  }
}
