/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateFormRequestFieldsInnerMaxSelectionAnyOf } from './CreateFormRequestFieldsInnerMaxSelectionAnyOf';
import {
    CreateFormRequestFieldsInnerMaxSelectionAnyOfFromJSON,
    CreateFormRequestFieldsInnerMaxSelectionAnyOfFromJSONTyped,
    CreateFormRequestFieldsInnerMaxSelectionAnyOfToJSON,
} from './CreateFormRequestFieldsInnerMaxSelectionAnyOf';

/**
 * 
 * @export
 * @interface CreateFormRequestFieldsInnerMaxSelection
 */
export interface CreateFormRequestFieldsInnerMaxSelection {
}

/**
 * Check if a given object implements the CreateFormRequestFieldsInnerMaxSelection interface.
 */
export function instanceOfCreateFormRequestFieldsInnerMaxSelection(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateFormRequestFieldsInnerMaxSelectionFromJSON(json: any): CreateFormRequestFieldsInnerMaxSelection {
    return CreateFormRequestFieldsInnerMaxSelectionFromJSONTyped(json, false);
}

export function CreateFormRequestFieldsInnerMaxSelectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFormRequestFieldsInnerMaxSelection {
    return json;
}

export function CreateFormRequestFieldsInnerMaxSelectionToJSON(value?: CreateFormRequestFieldsInnerMaxSelection | null): any {
    return value;
}

