/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateAttributeRequestConfigurationAnyOf } from './CreateAttributeRequestConfigurationAnyOf';
import {
    CreateAttributeRequestConfigurationAnyOfFromJSON,
    CreateAttributeRequestConfigurationAnyOfFromJSONTyped,
    CreateAttributeRequestConfigurationAnyOfToJSON,
} from './CreateAttributeRequestConfigurationAnyOf';
import type { CreateAttributeRequestConfigurationAnyOf1 } from './CreateAttributeRequestConfigurationAnyOf1';
import {
    CreateAttributeRequestConfigurationAnyOf1FromJSON,
    CreateAttributeRequestConfigurationAnyOf1FromJSONTyped,
    CreateAttributeRequestConfigurationAnyOf1ToJSON,
} from './CreateAttributeRequestConfigurationAnyOf1';
import type { CreateAttributeRequestConfigurationAnyOf2 } from './CreateAttributeRequestConfigurationAnyOf2';
import {
    CreateAttributeRequestConfigurationAnyOf2FromJSON,
    CreateAttributeRequestConfigurationAnyOf2FromJSONTyped,
    CreateAttributeRequestConfigurationAnyOf2ToJSON,
} from './CreateAttributeRequestConfigurationAnyOf2';
import type { CreateAttributeRequestConfigurationAnyOf3 } from './CreateAttributeRequestConfigurationAnyOf3';
import {
    CreateAttributeRequestConfigurationAnyOf3FromJSON,
    CreateAttributeRequestConfigurationAnyOf3FromJSONTyped,
    CreateAttributeRequestConfigurationAnyOf3ToJSON,
} from './CreateAttributeRequestConfigurationAnyOf3';
import type { CreateAttributeRequestConfigurationAnyOf4 } from './CreateAttributeRequestConfigurationAnyOf4';
import {
    CreateAttributeRequestConfigurationAnyOf4FromJSON,
    CreateAttributeRequestConfigurationAnyOf4FromJSONTyped,
    CreateAttributeRequestConfigurationAnyOf4ToJSON,
} from './CreateAttributeRequestConfigurationAnyOf4';
import type { CreateAttributeRequestConfigurationAnyOf5 } from './CreateAttributeRequestConfigurationAnyOf5';
import {
    CreateAttributeRequestConfigurationAnyOf5FromJSON,
    CreateAttributeRequestConfigurationAnyOf5FromJSONTyped,
    CreateAttributeRequestConfigurationAnyOf5ToJSON,
} from './CreateAttributeRequestConfigurationAnyOf5';
import type { CreateAttributeRequestConfigurationAnyOf6 } from './CreateAttributeRequestConfigurationAnyOf6';
import {
    CreateAttributeRequestConfigurationAnyOf6FromJSON,
    CreateAttributeRequestConfigurationAnyOf6FromJSONTyped,
    CreateAttributeRequestConfigurationAnyOf6ToJSON,
} from './CreateAttributeRequestConfigurationAnyOf6';
import type { CreateAttributeRequestConfigurationAnyOf7 } from './CreateAttributeRequestConfigurationAnyOf7';
import {
    CreateAttributeRequestConfigurationAnyOf7FromJSON,
    CreateAttributeRequestConfigurationAnyOf7FromJSONTyped,
    CreateAttributeRequestConfigurationAnyOf7ToJSON,
} from './CreateAttributeRequestConfigurationAnyOf7';

/**
 * 
 * @export
 * @interface CreateAttributeRequestConfiguration
 */
export interface CreateAttributeRequestConfiguration {
    /**
     * 
     * @type {string}
     * @memberof CreateAttributeRequestConfiguration
     */
    type: CreateAttributeRequestConfigurationTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateAttributeRequestConfiguration
     */
    textType?: CreateAttributeRequestConfigurationTextTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateAttributeRequestConfiguration
     */
    dateFormat: CreateAttributeRequestConfigurationDateFormatEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateAttributeRequestConfiguration
     */
    timeFormat: CreateAttributeRequestConfigurationTimeFormatEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateAttributeRequestConfiguration
     */
    format: CreateAttributeRequestConfigurationFormatEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateAttributeRequestConfiguration
     */
    style: CreateAttributeRequestConfigurationStyleEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateAttributeRequestConfiguration
     */
    options: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof CreateAttributeRequestConfiguration
     */
    isMultiSelect: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CreateAttributeRequestConfiguration
     */
    showFullUrl: boolean;
}

/**
* @export
* @enum {string}
*/
export enum CreateAttributeRequestConfigurationTypeEnum {
    Member = 'Member'
}
/**
* @export
* @enum {string}
*/
export enum CreateAttributeRequestConfigurationTextTypeEnum {
    SingleLine = 'single-line',
    MultiLine = 'multi-line',
    RichText = 'rich-text'
}
/**
* @export
* @enum {string}
*/
export enum CreateAttributeRequestConfigurationDateFormatEnum {
    FullDate = 'Full date',
    MonthDayYear = 'Month/Day/Year',
    DayMonthYear = 'Day/Month/Year',
    YearMonthDay = 'Year/Month/Day',
    Relative = 'Relative'
}
/**
* @export
* @enum {string}
*/
export enum CreateAttributeRequestConfigurationTimeFormatEnum {
    Hidden = 'Hidden',
    _12Hour = '12 hour',
    _24Hour = '24 hour'
}
/**
* @export
* @enum {string}
*/
export enum CreateAttributeRequestConfigurationFormatEnum {
    Number = 'Number',
    Percent = 'Percent',
    Currency = 'Currency'
}
/**
* @export
* @enum {string}
*/
export enum CreateAttributeRequestConfigurationStyleEnum {
    YesNo = 'Yes/No',
    Switch = 'Switch'
}


/**
 * Check if a given object implements the CreateAttributeRequestConfiguration interface.
 */
export function instanceOfCreateAttributeRequestConfiguration(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "dateFormat" in value;
    isInstance = isInstance && "timeFormat" in value;
    isInstance = isInstance && "format" in value;
    isInstance = isInstance && "style" in value;
    isInstance = isInstance && "options" in value;
    isInstance = isInstance && "isMultiSelect" in value;
    isInstance = isInstance && "showFullUrl" in value;

    return isInstance;
}

export function CreateAttributeRequestConfigurationFromJSON(json: any): CreateAttributeRequestConfiguration {
    return CreateAttributeRequestConfigurationFromJSONTyped(json, false);
}

export function CreateAttributeRequestConfigurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAttributeRequestConfiguration {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'textType': !exists(json, 'textType') ? undefined : json['textType'],
        'dateFormat': json['dateFormat'],
        'timeFormat': json['timeFormat'],
        'format': json['format'],
        'style': json['style'],
        'options': json['options'],
        'isMultiSelect': json['isMultiSelect'],
        'showFullUrl': json['showFullUrl'],
    };
}

export function CreateAttributeRequestConfigurationToJSON(value?: CreateAttributeRequestConfiguration | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'textType': value.textType,
        'dateFormat': value.dateFormat,
        'timeFormat': value.timeFormat,
        'format': value.format,
        'style': value.style,
        'options': value.options,
        'isMultiSelect': value.isMultiSelect,
        'showFullUrl': value.showFullUrl,
    };
}

