/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSavedItemRequest
 */
export interface CreateSavedItemRequest {
    /**
     * Optional name for the saved item
     * @type {string}
     * @memberof CreateSavedItemRequest
     */
    name?: string;
    /**
     * ID of the entity being saved
     * @type {string}
     * @memberof CreateSavedItemRequest
     */
    entityId: string;
    /**
     * Type of entity being saved (e.g., 'View', 'Candidate')
     * @type {string}
     * @memberof CreateSavedItemRequest
     */
    entityType: string;
    /**
     * Optional folder to add this saved item to
     * @type {string}
     * @memberof CreateSavedItemRequest
     */
    folderId?: string;
    /**
     * Whether this saved item is shared with the entire workspace
     * @type {boolean}
     * @memberof CreateSavedItemRequest
     */
    isSharedWithWorkspace?: boolean;
    /**
     * Profile IDs to share this saved item with
     * @type {Array<string>}
     * @memberof CreateSavedItemRequest
     */
    sharedWithProfileIds?: Array<string>;
}

/**
 * Check if a given object implements the CreateSavedItemRequest interface.
 */
export function instanceOfCreateSavedItemRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "entityId" in value;
    isInstance = isInstance && "entityType" in value;

    return isInstance;
}

export function CreateSavedItemRequestFromJSON(json: any): CreateSavedItemRequest {
    return CreateSavedItemRequestFromJSONTyped(json, false);
}

export function CreateSavedItemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSavedItemRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'entityId': json['entityId'],
        'entityType': json['entityType'],
        'folderId': !exists(json, 'folderId') ? undefined : json['folderId'],
        'isSharedWithWorkspace': !exists(json, 'isSharedWithWorkspace') ? undefined : json['isSharedWithWorkspace'],
        'sharedWithProfileIds': !exists(json, 'sharedWithProfileIds') ? undefined : json['sharedWithProfileIds'],
    };
}

export function CreateSavedItemRequestToJSON(value?: CreateSavedItemRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'entityId': value.entityId,
        'entityType': value.entityType,
        'folderId': value.folderId,
        'isSharedWithWorkspace': value.isSharedWithWorkspace,
        'sharedWithProfileIds': value.sharedWithProfileIds,
    };
}

