/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateMessageForInboundEmailRequest
 */
export interface CreateMessageForInboundEmailRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateMessageForInboundEmailRequest
     */
    data: { [key: string]: any; };
}

/**
 * Check if a given object implements the CreateMessageForInboundEmailRequest interface.
 */
export function instanceOfCreateMessageForInboundEmailRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function CreateMessageForInboundEmailRequestFromJSON(json: any): CreateMessageForInboundEmailRequest {
    return CreateMessageForInboundEmailRequestFromJSONTyped(json, false);
}

export function CreateMessageForInboundEmailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMessageForInboundEmailRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
            ...json,
        'data': json['data'],
    };
}

export function CreateMessageForInboundEmailRequestToJSON(value?: CreateMessageForInboundEmailRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
            ...value,
        'data': value.data,
    };
}

