/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
import type { GetApplications200ResponseInnerNotes } from "./GetApplications200ResponseInnerNotes"
import {
  GetApplications200ResponseInnerNotesFromJSON,
  GetApplications200ResponseInnerNotesFromJSONTyped,
  GetApplications200ResponseInnerNotesToJSON,
} from "./GetApplications200ResponseInnerNotes"

/**
 *
 * @export
 * @interface CreateOpening200Response
 */
export interface CreateOpening200Response {
  [key: string]: any | any
  /**
   *
   * @type {string}
   * @memberof CreateOpening200Response
   */
  id: string
  /**
   *
   * @type {Date}
   * @memberof CreateOpening200Response
   */
  updatedAt: Date
  /**
   *
   * @type {Date}
   * @memberof CreateOpening200Response
   */
  createdAt: Date
  /**
   *
   * @type {string}
   * @memberof CreateOpening200Response
   */
  title: string
  /**
   *
   * @type {GetApplications200ResponseInnerNotes}
   * @memberof CreateOpening200Response
   */
  description?: GetApplications200ResponseInnerNotes
  /**
   *
   * @type {string}
   * @memberof CreateOpening200Response
   */
  workspaceId: string
  /**
   *
   * @type {string}
   * @memberof CreateOpening200Response
   */
  roleId: string
  /**
   *
   * @type {any}
   * @memberof CreateOpening200Response
   */
  formId?: any | null
  /**
   *
   * @type {string}
   * @memberof CreateOpening200Response
   */
  status?: CreateOpening200ResponseStatusEnum
  /**
   *
   * @type {any}
   * @memberof CreateOpening200Response
   */
  deletedAt?: any | null
}

/**
 * @export
 * @enum {string}
 */
export enum CreateOpening200ResponseStatusEnum {
  Published = "Published",
  Draft = "Draft",
}

/**
 * Check if a given object implements the CreateOpening200Response interface.
 */
export function instanceOfCreateOpening200Response(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && "id" in value
  isInstance = isInstance && "updatedAt" in value
  isInstance = isInstance && "createdAt" in value
  isInstance = isInstance && "title" in value
  isInstance = isInstance && "workspaceId" in value
  isInstance = isInstance && "roleId" in value

  return isInstance
}

export function CreateOpening200ResponseFromJSON(
  json: any,
): CreateOpening200Response {
  return CreateOpening200ResponseFromJSONTyped(json, false)
}

export function CreateOpening200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateOpening200Response {
  if (json === undefined || json === null) {
    return json
  }
  return {
    ...json,
    id: json["id"],
    updatedAt: new Date(json["updatedAt"]),
    createdAt: new Date(json["createdAt"]),
    title: json["title"],
    description: !exists(json, "description")
      ? undefined
      : GetApplications200ResponseInnerNotesFromJSON(json["description"]),
    workspaceId: json["workspaceId"],
    roleId: json["roleId"],
    formId: !exists(json, "formId") ? undefined : json["formId"],
    status: !exists(json, "status") ? undefined : json["status"],
    deletedAt: !exists(json, "deletedAt") ? undefined : json["deletedAt"],
  }
}

export function CreateOpening200ResponseToJSON(
  value?: CreateOpening200Response | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    ...value,
    id: value.id,
    updatedAt: value.updatedAt.toISOString(),
    createdAt: value.createdAt.toISOString(),
    title: value.title,
    description: GetApplications200ResponseInnerNotesToJSON(value.description),
    workspaceId: value.workspaceId,
    roleId: value.roleId,
    formId: value.formId,
    status: value.status,
    deletedAt: value.deletedAt,
  }
}
