/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateAttributeRequestConfiguration } from './CreateAttributeRequestConfiguration';
import {
    CreateAttributeRequestConfigurationFromJSON,
    CreateAttributeRequestConfigurationFromJSONTyped,
    CreateAttributeRequestConfigurationToJSON,
} from './CreateAttributeRequestConfiguration';

/**
 * 
 * @export
 * @interface CreateAttributeRequest
 */
export interface CreateAttributeRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateAttributeRequest
     */
    entity: CreateAttributeRequestEntityEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateAttributeRequest
     */
    name: string;
    /**
     * 
     * @type {CreateAttributeRequestConfiguration}
     * @memberof CreateAttributeRequest
     */
    _configuration: CreateAttributeRequestConfiguration;
}

/**
* @export
* @enum {string}
*/
export enum CreateAttributeRequestEntityEnum {
    Role = 'Role',
    Opening = 'Opening',
    Application = 'Application',
    Candidate = 'Candidate',
    Custom = 'Custom'
}


/**
 * Check if a given object implements the CreateAttributeRequest interface.
 */
export function instanceOfCreateAttributeRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "entity" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "_configuration" in value;

    return isInstance;
}

export function CreateAttributeRequestFromJSON(json: any): CreateAttributeRequest {
    return CreateAttributeRequestFromJSONTyped(json, false);
}

export function CreateAttributeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAttributeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'entity': json['entity'],
        'name': json['name'],
        '_configuration': CreateAttributeRequestConfigurationFromJSON(json['configuration']),
    };
}

export function CreateAttributeRequestToJSON(value?: CreateAttributeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'entity': value.entity,
        'name': value.name,
        'configuration': CreateAttributeRequestConfigurationToJSON(value._configuration),
    };
}

