/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateApplicationRequest
 */
export interface CreateApplicationRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateApplicationRequest
     */
    candidate: string;
    /**
     * 
     * @type {string}
     * @memberof CreateApplicationRequest
     */
    opening: string;
}

/**
 * Check if a given object implements the CreateApplicationRequest interface.
 */
export function instanceOfCreateApplicationRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "candidate" in value;
    isInstance = isInstance && "opening" in value;

    return isInstance;
}

export function CreateApplicationRequestFromJSON(json: any): CreateApplicationRequest {
    return CreateApplicationRequestFromJSONTyped(json, false);
}

export function CreateApplicationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateApplicationRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'candidate': json['candidate'],
        'opening': json['opening'],
    };
}

export function CreateApplicationRequestToJSON(value?: CreateApplicationRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'candidate': value.candidate,
        'opening': value.opening,
    };
}

