/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
/**
 *
 * @export
 * @interface CreateProfile200ResponseWorkspace
 */
export interface CreateProfile200ResponseWorkspace {
  /**
   *
   * @type {string}
   * @memberof CreateProfile200ResponseWorkspace
   */
  url: string
  /**
   *
   * @type {string}
   * @memberof CreateProfile200ResponseWorkspace
   */
  name: string
}

/**
 * Check if a given object implements the CreateProfile200ResponseWorkspace interface.
 */
export function instanceOfCreateProfile200ResponseWorkspace(
  value: object,
): boolean {
  let isInstance = true
  isInstance = isInstance && "url" in value
  isInstance = isInstance && "name" in value

  return isInstance
}

export function CreateProfile200ResponseWorkspaceFromJSON(
  json: any,
): CreateProfile200ResponseWorkspace {
  return CreateProfile200ResponseWorkspaceFromJSONTyped(json, false)
}

export function CreateProfile200ResponseWorkspaceFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateProfile200ResponseWorkspace {
  if (json === undefined || json === null) {
    return json
  }
  return {
    url: json["url"],
    name: json["name"],
  }
}

export function CreateProfile200ResponseWorkspaceToJSON(
  value?: CreateProfile200ResponseWorkspace | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    url: value.url,
    name: value.name,
  }
}
