/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
import type { CreateWorkflowRequestDefinition } from "./CreateWorkflowRequestDefinition"
import {
  CreateWorkflowRequestDefinitionFromJSON,
  CreateWorkflowRequestDefinitionFromJSONTyped,
  CreateWorkflowRequestDefinitionToJSON,
} from "./CreateWorkflowRequestDefinition"

/**
 *
 * @export
 * @interface CreateWorkflowRequest
 */
export interface CreateWorkflowRequest {
  /**
   *
   * @type {string}
   * @memberof CreateWorkflowRequest
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof CreateWorkflowRequest
   */
  description?: string
  /**
   *
   * @type {CreateWorkflowRequestDefinition}
   * @memberof CreateWorkflowRequest
   */
  definition: CreateWorkflowRequestDefinition
}

/**
 * Check if a given object implements the CreateWorkflowRequest interface.
 */
export function instanceOfCreateWorkflowRequest(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && "name" in value
  isInstance = isInstance && "definition" in value

  return isInstance
}

export function CreateWorkflowRequestFromJSON(
  json: any,
): CreateWorkflowRequest {
  return CreateWorkflowRequestFromJSONTyped(json, false)
}

export function CreateWorkflowRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateWorkflowRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    name: json["name"],
    description: !exists(json, "description") ? undefined : json["description"],
    definition: CreateWorkflowRequestDefinitionFromJSON(json["definition"]),
  }
}

export function CreateWorkflowRequestToJSON(
  value?: CreateWorkflowRequest | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    name: value.name,
    description: value.description,
    definition: CreateWorkflowRequestDefinitionToJSON(value.definition),
  }
}
