/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Def0
 */
export interface Def0 {
    /**
     * 
     * @type {number}
     * @memberof Def0
     */
    statusCode?: number;
    /**
     * 
     * @type {string}
     * @memberof Def0
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof Def0
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof Def0
     */
    message?: string;
}

/**
 * Check if a given object implements the Def0 interface.
 */
export function instanceOfDef0(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function Def0FromJSON(json: any): Def0 {
    return Def0FromJSONTyped(json, false);
}

export function Def0FromJSONTyped(json: any, ignoreDiscriminator: boolean): Def0 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'statusCode': !exists(json, 'statusCode') ? undefined : json['statusCode'],
        'code': !exists(json, 'code') ? undefined : json['code'],
        'error': !exists(json, 'error') ? undefined : json['error'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function Def0ToJSON(value?: Def0 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'statusCode': value.statusCode,
        'code': value.code,
        'error': value.error,
        'message': value.message,
    };
}

