/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteSelectOptionRequest
 */
export interface DeleteSelectOptionRequest {
    /**
     * 
     * @type {string}
     * @memberof DeleteSelectOptionRequest
     */
    option: string;
}

/**
 * Check if a given object implements the DeleteSelectOptionRequest interface.
 */
export function instanceOfDeleteSelectOptionRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "option" in value;

    return isInstance;
}

export function DeleteSelectOptionRequestFromJSON(json: any): DeleteSelectOptionRequest {
    return DeleteSelectOptionRequestFromJSONTyped(json, false);
}

export function DeleteSelectOptionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteSelectOptionRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'option': json['option'],
    };
}

export function DeleteSelectOptionRequestToJSON(value?: DeleteSelectOptionRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'option': value.option,
    };
}

