/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
/**
 *
 * @export
 * @interface DeleteWorkflow400Response
 */
export interface DeleteWorkflow400Response {
  /**
   *
   * @type {number}
   * @memberof DeleteWorkflow400Response
   */
  statusCode?: number
  /**
   *
   * @type {string}
   * @memberof DeleteWorkflow400Response
   */
  error?: string
  /**
   *
   * @type {string}
   * @memberof DeleteWorkflow400Response
   */
  message?: string
}

/**
 * Check if a given object implements the DeleteWorkflow400Response interface.
 */
export function instanceOfDeleteWorkflow400Response(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function DeleteWorkflow400ResponseFromJSON(
  json: any,
): DeleteWorkflow400Response {
  return DeleteWorkflow400ResponseFromJSONTyped(json, false)
}

export function DeleteWorkflow400ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DeleteWorkflow400Response {
  if (json === undefined || json === null) {
    return json
  }
  return {
    statusCode: !exists(json, "statusCode") ? undefined : json["statusCode"],
    error: !exists(json, "error") ? undefined : json["error"],
    message: !exists(json, "message") ? undefined : json["message"],
  }
}

export function DeleteWorkflow400ResponseToJSON(
  value?: DeleteWorkflow400Response | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    statusCode: value.statusCode,
    error: value.error,
    message: value.message,
  }
}
