/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
import type { WorkspaceCalendarAvailableSlotsGet200ResponseSlotsInner } from "./WorkspaceCalendarAvailableSlotsGet200ResponseSlotsInner"
import {
  WorkspaceCalendarAvailableSlotsGet200ResponseSlotsInnerFromJSON,
  WorkspaceCalendarAvailableSlotsGet200ResponseSlotsInnerFromJSONTyped,
  WorkspaceCalendarAvailableSlotsGet200ResponseSlotsInnerToJSON,
} from "./WorkspaceCalendarAvailableSlotsGet200ResponseSlotsInner"

/**
 *
 * @export
 * @interface GetAvailableMeetingSlots200Response
 */
export interface GetAvailableMeetingSlots200Response {
  /**
   *
   * @type {Array<WorkspaceCalendarAvailableSlotsGet200ResponseSlotsInner>}
   * @memberof GetAvailableMeetingSlots200Response
   */
  availableSlots?: Array<WorkspaceCalendarAvailableSlotsGet200ResponseSlotsInner>
  /**
   *
   * @type {string}
   * @memberof GetAvailableMeetingSlots200Response
   */
  timezone?: string
}

/**
 * Check if a given object implements the GetAvailableMeetingSlots200Response interface.
 */
export function instanceOfGetAvailableMeetingSlots200Response(
  value: object,
): boolean {
  let isInstance = true

  return isInstance
}

export function GetAvailableMeetingSlots200ResponseFromJSON(
  json: any,
): GetAvailableMeetingSlots200Response {
  return GetAvailableMeetingSlots200ResponseFromJSONTyped(json, false)
}

export function GetAvailableMeetingSlots200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetAvailableMeetingSlots200Response {
  if (json === undefined || json === null) {
    return json
  }
  return {
    availableSlots: !exists(json, "availableSlots")
      ? undefined
      : (json["availableSlots"] as Array<any>).map(
          WorkspaceCalendarAvailableSlotsGet200ResponseSlotsInnerFromJSON,
        ),
    timezone: !exists(json, "timezone") ? undefined : json["timezone"],
  }
}

export function GetAvailableMeetingSlots200ResponseToJSON(
  value?: GetAvailableMeetingSlots200Response | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    availableSlots:
      value.availableSlots === undefined
        ? undefined
        : (value.availableSlots as Array<any>).map(
            WorkspaceCalendarAvailableSlotsGet200ResponseSlotsInnerToJSON,
          ),
    timezone: value.timezone,
  }
}
