/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAttributes200ResponseInner
 */
export interface GetAttributes200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof GetAttributes200ResponseInner
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof GetAttributes200ResponseInner
     */
    updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetAttributes200ResponseInner
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof GetAttributes200ResponseInner
     */
    entityType: GetAttributes200ResponseInnerEntityTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GetAttributes200ResponseInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GetAttributes200ResponseInner
     */
    dataType: GetAttributes200ResponseInnerDataTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GetAttributes200ResponseInner
     */
    workspaceId: string;
    /**
     * 
     * @type {string}
     * @memberof GetAttributes200ResponseInner
     */
    creatorId: string;
    /**
     * 
     * @type {any}
     * @memberof GetAttributes200ResponseInner
     */
    entityId?: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof GetAttributes200ResponseInner
     */
    builtIn: boolean;
    /**
     * 
     * @type {any}
     * @memberof GetAttributes200ResponseInner
     */
    _configuration?: any | null;
}

/**
* @export
* @enum {string}
*/
export enum GetAttributes200ResponseInnerEntityTypeEnum {
    Role = 'Role',
    Opening = 'Opening',
    Application = 'Application',
    Candidate = 'Candidate',
    Custom = 'Custom'
}
/**
* @export
* @enum {string}
*/
export enum GetAttributes200ResponseInnerDataTypeEnum {
    Text = 'Text',
    Number = 'Number',
    Toggle = 'Toggle',
    Select = 'Select',
    Date = 'Date',
    Email = 'Email',
    Url = 'URL',
    File = 'File',
    Phone = 'Phone',
    Record = 'Record',
    Range = 'Range',
    Location = 'Location',
    Member = 'Member'
}


/**
 * Check if a given object implements the GetAttributes200ResponseInner interface.
 */
export function instanceOfGetAttributes200ResponseInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "updatedAt" in value;
    isInstance = isInstance && "entityType" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "dataType" in value;
    isInstance = isInstance && "workspaceId" in value;
    isInstance = isInstance && "creatorId" in value;
    isInstance = isInstance && "builtIn" in value;

    return isInstance;
}

export function GetAttributes200ResponseInnerFromJSON(json: any): GetAttributes200ResponseInner {
    return GetAttributes200ResponseInnerFromJSONTyped(json, false);
}

export function GetAttributes200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAttributes200ResponseInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'updatedAt': (new Date(json['updatedAt'])),
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'entityType': json['entityType'],
        'name': json['name'],
        'dataType': json['dataType'],
        'workspaceId': json['workspaceId'],
        'creatorId': json['creatorId'],
        'entityId': !exists(json, 'entityId') ? undefined : json['entityId'],
        'builtIn': json['builtIn'],
        '_configuration': !exists(json, 'configuration') ? undefined : json['configuration'],
    };
}

export function GetAttributes200ResponseInnerToJSON(value?: GetAttributes200ResponseInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'updatedAt': (value.updatedAt.toISOString()),
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'entityType': value.entityType,
        'name': value.name,
        'dataType': value.dataType,
        'workspaceId': value.workspaceId,
        'creatorId': value.creatorId,
        'entityId': value.entityId,
        'builtIn': value.builtIn,
        'configuration': value._configuration,
    };
}

