/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetApplications200ResponseInnerNotes
 */
export interface GetApplications200ResponseInnerNotes {
    /**
     * 
     * @type {string}
     * @memberof GetApplications200ResponseInnerNotes
     */
    html: string;
    /**
     * 
     * @type {object}
     * @memberof GetApplications200ResponseInnerNotes
     */
    json: object;
}

/**
 * Check if a given object implements the GetApplications200ResponseInnerNotes interface.
 */
export function instanceOfGetApplications200ResponseInnerNotes(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "html" in value;
    isInstance = isInstance && "json" in value;

    return isInstance;
}

export function GetApplications200ResponseInnerNotesFromJSON(json: any): GetApplications200ResponseInnerNotes {
    return GetApplications200ResponseInnerNotesFromJSONTyped(json, false);
}

export function GetApplications200ResponseInnerNotesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetApplications200ResponseInnerNotes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'html': json['html'],
        'json': json['json'],
    };
}

export function GetApplications200ResponseInnerNotesToJSON(value?: GetApplications200ResponseInnerNotes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'html': value.html,
        'json': value.json,
    };
}

