/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetCurrentUser200ResponseData } from './GetCurrentUser200ResponseData';
import {
    GetCurrentUser200ResponseDataFromJSON,
    GetCurrentUser200ResponseDataFromJSONTyped,
    GetCurrentUser200ResponseDataToJSON,
} from './GetCurrentUser200ResponseData';
import type { GetCurrentUser200ResponseMeta } from './GetCurrentUser200ResponseMeta';
import {
    GetCurrentUser200ResponseMetaFromJSON,
    GetCurrentUser200ResponseMetaFromJSONTyped,
    GetCurrentUser200ResponseMetaToJSON,
} from './GetCurrentUser200ResponseMeta';

/**
 * 
 * @export
 * @interface GetCurrentUser200Response
 */
export interface GetCurrentUser200Response {
    /**
     * 
     * @type {GetCurrentUser200ResponseData}
     * @memberof GetCurrentUser200Response
     */
    data: GetCurrentUser200ResponseData;
    /**
     * 
     * @type {GetCurrentUser200ResponseMeta}
     * @memberof GetCurrentUser200Response
     */
    meta?: GetCurrentUser200ResponseMeta;
}

/**
 * Check if a given object implements the GetCurrentUser200Response interface.
 */
export function instanceOfGetCurrentUser200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function GetCurrentUser200ResponseFromJSON(json: any): GetCurrentUser200Response {
    return GetCurrentUser200ResponseFromJSONTyped(json, false);
}

export function GetCurrentUser200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCurrentUser200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': GetCurrentUser200ResponseDataFromJSON(json['data']),
        'meta': !exists(json, 'meta') ? undefined : GetCurrentUser200ResponseMetaFromJSON(json['meta']),
    };
}

export function GetCurrentUser200ResponseToJSON(value?: GetCurrentUser200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': GetCurrentUser200ResponseDataToJSON(value.data),
        'meta': GetCurrentUser200ResponseMetaToJSON(value.meta),
    };
}

