/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
/**
 *
 * @export
 * @interface GetForms200ResponseInnerOpeningsInnerDescription
 */
export interface GetForms200ResponseInnerOpeningsInnerDescription {
  /**
   *
   * @type {string}
   * @memberof GetForms200ResponseInnerOpeningsInnerDescription
   */
  html: string
  /**
   *
   * @type {object}
   * @memberof GetForms200ResponseInnerOpeningsInnerDescription
   */
  json: object
}

/**
 * Check if a given object implements the GetForms200ResponseInnerOpeningsInnerDescription interface.
 */
export function instanceOfGetForms200ResponseInnerOpeningsInnerDescription(
  value: object,
): boolean {
  let isInstance = true
  isInstance = isInstance && "html" in value
  isInstance = isInstance && "json" in value

  return isInstance
}

export function GetForms200ResponseInnerOpeningsInnerDescriptionFromJSON(
  json: any,
): GetForms200ResponseInnerOpeningsInnerDescription {
  return GetForms200ResponseInnerOpeningsInnerDescriptionFromJSONTyped(
    json,
    false,
  )
}

export function GetForms200ResponseInnerOpeningsInnerDescriptionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetForms200ResponseInnerOpeningsInnerDescription {
  if (json === undefined || json === null) {
    return json
  }
  return {
    html: json["html"],
    json: json["json"],
  }
}

export function GetForms200ResponseInnerOpeningsInnerDescriptionToJSON(
  value?: GetForms200ResponseInnerOpeningsInnerDescription | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    html: value.html,
    json: value.json,
  }
}
