/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
/**
 *
 * @export
 * @interface GetInbox200ResponseInner
 */
export interface GetInbox200ResponseInner {
  /**
   *
   * @type {string}
   * @memberof GetInbox200ResponseInner
   */
  id: string
  /**
   *
   * @type {Date}
   * @memberof GetInbox200ResponseInner
   */
  createdAt: Date
  /**
   *
   * @type {string}
   * @memberof GetInbox200ResponseInner
   */
  type: GetInbox200ResponseInnerTypeEnum
  /**
   *
   * @type {string}
   * @memberof GetInbox200ResponseInner
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof GetInbox200ResponseInner
   */
  description: string
}

/**
 * @export
 * @enum {string}
 */
export enum GetInbox200ResponseInnerTypeEnum {
  InboundEmail = "InboundEmail",
  Review = "Review",
  Decide = "Decide",
  Meeting = "Meeting",
}

/**
 * Check if a given object implements the GetInbox200ResponseInner interface.
 */
export function instanceOfGetInbox200ResponseInner(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && "id" in value
  isInstance = isInstance && "createdAt" in value
  isInstance = isInstance && "type" in value
  isInstance = isInstance && "name" in value
  isInstance = isInstance && "description" in value

  return isInstance
}

export function GetInbox200ResponseInnerFromJSON(
  json: any,
): GetInbox200ResponseInner {
  return GetInbox200ResponseInnerFromJSONTyped(json, false)
}

export function GetInbox200ResponseInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetInbox200ResponseInner {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: json["id"],
    createdAt: new Date(json["createdAt"]),
    type: json["type"],
    name: json["name"],
    description: json["description"],
  }
}

export function GetInbox200ResponseInnerToJSON(
  value?: GetInbox200ResponseInner | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id,
    createdAt: value.createdAt.toISOString(),
    type: value.type,
    name: value.name,
    description: value.description,
  }
}
