/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetLandingData200ResponseOpeningsInner } from './GetLandingData200ResponseOpeningsInner';
import {
    GetLandingData200ResponseOpeningsInnerFromJSON,
    GetLandingData200ResponseOpeningsInnerFromJSONTyped,
    GetLandingData200ResponseOpeningsInnerToJSON,
} from './GetLandingData200ResponseOpeningsInner';
import type { GetOpening200Response1Content } from './GetOpening200Response1Content';
import {
    GetOpening200Response1ContentFromJSON,
    GetOpening200Response1ContentFromJSONTyped,
    GetOpening200Response1ContentToJSON,
} from './GetOpening200Response1Content';
import type { GetOpening200Response1Workspace } from './GetOpening200Response1Workspace';
import {
    GetOpening200Response1WorkspaceFromJSON,
    GetOpening200Response1WorkspaceFromJSONTyped,
    GetOpening200Response1WorkspaceToJSON,
} from './GetOpening200Response1Workspace';

/**
 * 
 * @export
 * @interface GetLandingData200Response
 */
export interface GetLandingData200Response {
    /**
     * 
     * @type {GetOpening200Response1Workspace}
     * @memberof GetLandingData200Response
     */
    workspace: GetOpening200Response1Workspace;
    /**
     * 
     * @type {GetOpening200Response1Content}
     * @memberof GetLandingData200Response
     */
    content: GetOpening200Response1Content;
    /**
     * 
     * @type {Array<GetLandingData200ResponseOpeningsInner>}
     * @memberof GetLandingData200Response
     */
    openings: Array<GetLandingData200ResponseOpeningsInner>;
}

/**
 * Check if a given object implements the GetLandingData200Response interface.
 */
export function instanceOfGetLandingData200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "workspace" in value;
    isInstance = isInstance && "content" in value;
    isInstance = isInstance && "openings" in value;

    return isInstance;
}

export function GetLandingData200ResponseFromJSON(json: any): GetLandingData200Response {
    return GetLandingData200ResponseFromJSONTyped(json, false);
}

export function GetLandingData200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetLandingData200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'workspace': GetOpening200Response1WorkspaceFromJSON(json['workspace']),
        'content': GetOpening200Response1ContentFromJSON(json['content']),
        'openings': ((json['openings'] as Array<any>).map(GetLandingData200ResponseOpeningsInnerFromJSON)),
    };
}

export function GetLandingData200ResponseToJSON(value?: GetLandingData200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'workspace': GetOpening200Response1WorkspaceToJSON(value.workspace),
        'content': GetOpening200Response1ContentToJSON(value.content),
        'openings': ((value.openings as Array<any>).map(GetLandingData200ResponseOpeningsInnerToJSON)),
    };
}

