/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetMessages200ResponseInner } from './GetMessages200ResponseInner';
import {
    GetMessages200ResponseInnerFromJSON,
    GetMessages200ResponseInnerFromJSONTyped,
    GetMessages200ResponseInnerToJSON,
} from './GetMessages200ResponseInner';

/**
 * 
 * @export
 * @interface GetMessage200Response
 */
export interface GetMessage200Response {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof GetMessage200Response
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof GetMessage200Response
     */
    updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetMessage200Response
     */
    createdAt: Date;
    /**
     * 
     * @type {any}
     * @memberof GetMessage200Response
     */
    deletedAt?: any | null;
    /**
     * 
     * @type {string}
     * @memberof GetMessage200Response
     */
    type: GetMessage200ResponseTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GetMessage200Response
     */
    status?: GetMessage200ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof GetMessage200Response
     */
    content: string;
    /**
     * 
     * @type {any}
     * @memberof GetMessage200Response
     */
    applicationId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GetMessage200Response
     */
    fromCandidateId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GetMessage200Response
     */
    conversationId?: any | null;
    /**
     * 
     * @type {string}
     * @memberof GetMessage200Response
     */
    workspaceId: string;
    /**
     * 
     * @type {any}
     * @memberof GetMessage200Response
     */
    authorId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GetMessage200Response
     */
    parentId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GetMessage200Response
     */
    metadata: any | null;
    /**
     * 
     * @type {any}
     * @memberof GetMessage200Response
     */
    attachments?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GetMessage200Response
     */
    subject?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GetMessage200Response
     */
    fromEmail?: any | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetMessage200Response
     */
    toEmails: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetMessage200Response
     */
    ccEmails: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetMessage200Response
     */
    bccEmails: Array<string>;
    /**
     * 
     * @type {GetMessages200ResponseInner}
     * @memberof GetMessage200Response
     */
    parent?: GetMessages200ResponseInner;
}

/**
* @export
* @enum {string}
*/
export enum GetMessage200ResponseTypeEnum {
    EmailOutbound = 'EMAIL_OUTBOUND',
    EmailInbound = 'EMAIL_INBOUND',
    InternalMessage = 'INTERNAL_MESSAGE',
    InternalResponse = 'INTERNAL_RESPONSE',
    Platform = 'PLATFORM'
}
/**
* @export
* @enum {string}
*/
export enum GetMessage200ResponseStatusEnum {
    Draft = 'DRAFT',
    Sending = 'SENDING',
    Sent = 'SENT',
    Published = 'PUBLISHED',
    Delivered = 'DELIVERED',
    Failed = 'FAILED',
    Bounced = 'BOUNCED',
    Archived = 'ARCHIVED'
}


/**
 * Check if a given object implements the GetMessage200Response interface.
 */
export function instanceOfGetMessage200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "updatedAt" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "content" in value;
    isInstance = isInstance && "workspaceId" in value;
    isInstance = isInstance && "metadata" in value;
    isInstance = isInstance && "toEmails" in value;
    isInstance = isInstance && "ccEmails" in value;
    isInstance = isInstance && "bccEmails" in value;

    return isInstance;
}

export function GetMessage200ResponseFromJSON(json: any): GetMessage200Response {
    return GetMessage200ResponseFromJSONTyped(json, false);
}

export function GetMessage200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMessage200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'updatedAt': (new Date(json['updatedAt'])),
        'createdAt': (new Date(json['createdAt'])),
        'deletedAt': !exists(json, 'deletedAt') ? undefined : json['deletedAt'],
        'type': json['type'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'content': json['content'],
        'applicationId': !exists(json, 'applicationId') ? undefined : json['applicationId'],
        'fromCandidateId': !exists(json, 'fromCandidateId') ? undefined : json['fromCandidateId'],
        'conversationId': !exists(json, 'conversationId') ? undefined : json['conversationId'],
        'workspaceId': json['workspaceId'],
        'authorId': !exists(json, 'authorId') ? undefined : json['authorId'],
        'parentId': !exists(json, 'parentId') ? undefined : json['parentId'],
        'metadata': json['metadata'],
        'attachments': !exists(json, 'attachments') ? undefined : json['attachments'],
        'subject': !exists(json, 'subject') ? undefined : json['subject'],
        'fromEmail': !exists(json, 'fromEmail') ? undefined : json['fromEmail'],
        'toEmails': json['toEmails'],
        'ccEmails': json['ccEmails'],
        'bccEmails': json['bccEmails'],
        'parent': !exists(json, 'parent') ? undefined : GetMessages200ResponseInnerFromJSON(json['parent']),
    };
}

export function GetMessage200ResponseToJSON(value?: GetMessage200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
            ...value,
        'id': value.id,
        'updatedAt': (value.updatedAt.toISOString()),
        'createdAt': (value.createdAt.toISOString()),
        'deletedAt': value.deletedAt,
        'type': value.type,
        'status': value.status,
        'content': value.content,
        'applicationId': value.applicationId,
        'fromCandidateId': value.fromCandidateId,
        'conversationId': value.conversationId,
        'workspaceId': value.workspaceId,
        'authorId': value.authorId,
        'parentId': value.parentId,
        'metadata': value.metadata,
        'attachments': value.attachments,
        'subject': value.subject,
        'fromEmail': value.fromEmail,
        'toEmails': value.toEmails,
        'ccEmails': value.ccEmails,
        'bccEmails': value.bccEmails,
        'parent': GetMessages200ResponseInnerToJSON(value.parent),
    };
}

