/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
/**
 *
 * @export
 * @interface GetMeetingNotes200ResponseMeetingNotesInner
 */
export interface GetMeetingNotes200ResponseMeetingNotesInner {
  /**
   *
   * @type {string}
   * @memberof GetMeetingNotes200ResponseMeetingNotesInner
   */
  id: string
  /**
   *
   * @type {string}
   * @memberof GetMeetingNotes200ResponseMeetingNotesInner
   */
  content: string
  /**
   *
   * @type {Date}
   * @memberof GetMeetingNotes200ResponseMeetingNotesInner
   */
  createdAt?: Date
  /**
   *
   * @type {Date}
   * @memberof GetMeetingNotes200ResponseMeetingNotesInner
   */
  updatedAt: Date
  /**
   *
   * @type {any}
   * @memberof GetMeetingNotes200ResponseMeetingNotesInner
   */
  meetingId?: any | null
  /**
   *
   * @type {string}
   * @memberof GetMeetingNotes200ResponseMeetingNotesInner
   */
  profileId: string
  /**
   *
   * @type {string}
   * @memberof GetMeetingNotes200ResponseMeetingNotesInner
   */
  workspaceId: string
  /**
   *
   * @type {any}
   * @memberof GetMeetingNotes200ResponseMeetingNotesInner
   */
  applicationId?: any | null
}

/**
 * Check if a given object implements the GetMeetingNotes200ResponseMeetingNotesInner interface.
 */
export function instanceOfGetMeetingNotes200ResponseMeetingNotesInner(
  value: object,
): boolean {
  let isInstance = true
  isInstance = isInstance && "id" in value
  isInstance = isInstance && "content" in value
  isInstance = isInstance && "updatedAt" in value
  isInstance = isInstance && "profileId" in value
  isInstance = isInstance && "workspaceId" in value

  return isInstance
}

export function GetMeetingNotes200ResponseMeetingNotesInnerFromJSON(
  json: any,
): GetMeetingNotes200ResponseMeetingNotesInner {
  return GetMeetingNotes200ResponseMeetingNotesInnerFromJSONTyped(json, false)
}

export function GetMeetingNotes200ResponseMeetingNotesInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetMeetingNotes200ResponseMeetingNotesInner {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: json["id"],
    content: json["content"],
    createdAt: !exists(json, "createdAt")
      ? undefined
      : new Date(json["createdAt"]),
    updatedAt: new Date(json["updatedAt"]),
    meetingId: !exists(json, "meetingId") ? undefined : json["meetingId"],
    profileId: json["profileId"],
    workspaceId: json["workspaceId"],
    applicationId: !exists(json, "applicationId")
      ? undefined
      : json["applicationId"],
  }
}

export function GetMeetingNotes200ResponseMeetingNotesInnerToJSON(
  value?: GetMeetingNotes200ResponseMeetingNotesInner | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id,
    content: value.content,
    createdAt:
      value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
    updatedAt: value.updatedAt.toISOString(),
    meetingId: value.meetingId,
    profileId: value.profileId,
    workspaceId: value.workspaceId,
    applicationId: value.applicationId,
  }
}
