/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
import type { GetApplications200ResponseInnerNotes } from "./GetApplications200ResponseInnerNotes"
import {
  GetApplications200ResponseInnerNotesFromJSON,
  GetApplications200ResponseInnerNotesFromJSONTyped,
  GetApplications200ResponseInnerNotesToJSON,
} from "./GetApplications200ResponseInnerNotes"
import type { GetOpenings200Response1InnerRole } from "./GetOpenings200Response1InnerRole"
import {
  GetOpenings200Response1InnerRoleFromJSON,
  GetOpenings200Response1InnerRoleFromJSONTyped,
  GetOpenings200Response1InnerRoleToJSON,
} from "./GetOpenings200Response1InnerRole"

/**
 *
 * @export
 * @interface GetOpenings200Response1Inner
 */
export interface GetOpenings200Response1Inner {
  [key: string]: any | any
  /**
   *
   * @type {string}
   * @memberof GetOpenings200Response1Inner
   */
  id: string
  /**
   *
   * @type {Date}
   * @memberof GetOpenings200Response1Inner
   */
  updatedAt: Date
  /**
   *
   * @type {Date}
   * @memberof GetOpenings200Response1Inner
   */
  createdAt: Date
  /**
   *
   * @type {string}
   * @memberof GetOpenings200Response1Inner
   */
  title: string
  /**
   *
   * @type {GetApplications200ResponseInnerNotes}
   * @memberof GetOpenings200Response1Inner
   */
  description?: GetApplications200ResponseInnerNotes
  /**
   *
   * @type {string}
   * @memberof GetOpenings200Response1Inner
   */
  workspaceId: string
  /**
   *
   * @type {string}
   * @memberof GetOpenings200Response1Inner
   */
  roleId: string
  /**
   *
   * @type {any}
   * @memberof GetOpenings200Response1Inner
   */
  formId?: any | null
  /**
   *
   * @type {string}
   * @memberof GetOpenings200Response1Inner
   */
  workflowId: string
  /**
   *
   * @type {string}
   * @memberof GetOpenings200Response1Inner
   */
  status?: GetOpenings200Response1InnerStatusEnum
  /**
   *
   * @type {any}
   * @memberof GetOpenings200Response1Inner
   */
  deletedAt?: any | null
  /**
   *
   * @type {GetOpenings200Response1InnerRole}
   * @memberof GetOpenings200Response1Inner
   */
  role: GetOpenings200Response1InnerRole
  /**
   *
   * @type {number}
   * @memberof GetOpenings200Response1Inner
   */
  applicationsCount: number
}

/**
 * @export
 * @enum {string}
 */
export enum GetOpenings200Response1InnerStatusEnum {
  Published = "Published",
  Draft = "Draft",
}

/**
 * Check if a given object implements the GetOpenings200Response1Inner interface.
 */
export function instanceOfGetOpenings200Response1Inner(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && "id" in value
  isInstance = isInstance && "updatedAt" in value
  isInstance = isInstance && "createdAt" in value
  isInstance = isInstance && "title" in value
  isInstance = isInstance && "workspaceId" in value
  isInstance = isInstance && "roleId" in value
  isInstance = isInstance && "workflowId" in value
  isInstance = isInstance && "role" in value
  isInstance = isInstance && "applicationsCount" in value

  return isInstance
}

export function GetOpenings200Response1InnerFromJSON(
  json: any,
): GetOpenings200Response1Inner {
  return GetOpenings200Response1InnerFromJSONTyped(json, false)
}

export function GetOpenings200Response1InnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetOpenings200Response1Inner {
  if (json === undefined || json === null) {
    return json
  }
  return {
    ...json,
    id: json["id"],
    updatedAt: new Date(json["updatedAt"]),
    createdAt: new Date(json["createdAt"]),
    title: json["title"],
    description: !exists(json, "description")
      ? undefined
      : GetApplications200ResponseInnerNotesFromJSON(json["description"]),
    workspaceId: json["workspaceId"],
    roleId: json["roleId"],
    formId: !exists(json, "formId") ? undefined : json["formId"],
    workflowId: json["workflowId"],
    status: !exists(json, "status") ? undefined : json["status"],
    deletedAt: !exists(json, "deletedAt") ? undefined : json["deletedAt"],
    role: GetOpenings200Response1InnerRoleFromJSON(json["role"]),
    applicationsCount: json["applicationsCount"],
  }
}

export function GetOpenings200Response1InnerToJSON(
  value?: GetOpenings200Response1Inner | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    ...value,
    id: value.id,
    updatedAt: value.updatedAt.toISOString(),
    createdAt: value.createdAt.toISOString(),
    title: value.title,
    description: GetApplications200ResponseInnerNotesToJSON(value.description),
    workspaceId: value.workspaceId,
    roleId: value.roleId,
    formId: value.formId,
    workflowId: value.workflowId,
    status: value.status,
    deletedAt: value.deletedAt,
    role: GetOpenings200Response1InnerRoleToJSON(value.role),
    applicationsCount: value.applicationsCount,
  }
}
