/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
/**
 *
 * @export
 * @interface GetOpening200ResponseWorkspace
 */
export interface GetOpening200ResponseWorkspace {
  /**
   *
   * @type {string}
   * @memberof GetOpening200ResponseWorkspace
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof GetOpening200ResponseWorkspace
   */
  logo?: string
}

/**
 * Check if a given object implements the GetOpening200ResponseWorkspace interface.
 */
export function instanceOfGetOpening200ResponseWorkspace(
  value: object,
): boolean {
  let isInstance = true
  isInstance = isInstance && "name" in value

  return isInstance
}

export function GetOpening200ResponseWorkspaceFromJSON(
  json: any,
): GetOpening200ResponseWorkspace {
  return GetOpening200ResponseWorkspaceFromJSONTyped(json, false)
}

export function GetOpening200ResponseWorkspaceFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetOpening200ResponseWorkspace {
  if (json === undefined || json === null) {
    return json
  }
  return {
    name: json["name"],
    logo: !exists(json, "logo") ? undefined : json["logo"],
  }
}

export function GetOpening200ResponseWorkspaceToJSON(
  value?: GetOpening200ResponseWorkspace | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    name: value.name,
    logo: value.logo,
  }
}
