/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
/**
 *
 * @export
 * @interface GetOpenings200ResponseDataInner
 */
export interface GetOpenings200ResponseDataInner {
  /**
   *
   * @type {string}
   * @memberof GetOpenings200ResponseDataInner
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof GetOpenings200ResponseDataInner
   */
  title?: string
  /**
   *
   * @type {string}
   * @memberof GetOpenings200ResponseDataInner
   */
  status?: string
  /**
   *
   * @type {Date}
   * @memberof GetOpenings200ResponseDataInner
   */
  createdAt?: Date
  /**
   *
   * @type {string}
   * @memberof GetOpenings200ResponseDataInner
   */
  publicUrl?: string
  /**
   *
   * @type {number}
   * @memberof GetOpenings200ResponseDataInner
   */
  applicationsCount?: number
  /**
   *
   * @type {{ [key: string]: any; }}
   * @memberof GetOpenings200ResponseDataInner
   */
  customFields?: { [key: string]: any }
}

/**
 * Check if a given object implements the GetOpenings200ResponseDataInner interface.
 */
export function instanceOfGetOpenings200ResponseDataInner(
  value: object,
): boolean {
  let isInstance = true

  return isInstance
}

export function GetOpenings200ResponseDataInnerFromJSON(
  json: any,
): GetOpenings200ResponseDataInner {
  return GetOpenings200ResponseDataInnerFromJSONTyped(json, false)
}

export function GetOpenings200ResponseDataInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetOpenings200ResponseDataInner {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    title: !exists(json, "title") ? undefined : json["title"],
    status: !exists(json, "status") ? undefined : json["status"],
    createdAt: !exists(json, "createdAt")
      ? undefined
      : new Date(json["createdAt"]),
    publicUrl: !exists(json, "publicUrl") ? undefined : json["publicUrl"],
    applicationsCount: !exists(json, "applicationsCount")
      ? undefined
      : json["applicationsCount"],
    customFields: !exists(json, "customFields")
      ? undefined
      : json["customFields"],
  }
}

export function GetOpenings200ResponseDataInnerToJSON(
  value?: GetOpenings200ResponseDataInner | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id,
    title: value.title,
    status: value.status,
    createdAt:
      value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
    publicUrl: value.publicUrl,
    applicationsCount: value.applicationsCount,
    customFields: value.customFields,
  }
}
