/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
import type { GetApplications200ResponseInnerNotes } from "./GetApplications200ResponseInnerNotes"
import {
  GetApplications200ResponseInnerNotesFromJSON,
  GetApplications200ResponseInnerNotesFromJSONTyped,
  GetApplications200ResponseInnerNotesToJSON,
} from "./GetApplications200ResponseInnerNotes"

/**
 *
 * @export
 * @interface GetOpenings200Response1InnerRole
 */
export interface GetOpenings200Response1InnerRole {
  [key: string]: any | any
  /**
   *
   * @type {string}
   * @memberof GetOpenings200Response1InnerRole
   */
  id: string
  /**
   *
   * @type {Date}
   * @memberof GetOpenings200Response1InnerRole
   */
  updatedAt: Date
  /**
   *
   * @type {Date}
   * @memberof GetOpenings200Response1InnerRole
   */
  createdAt?: Date
  /**
   *
   * @type {string}
   * @memberof GetOpenings200Response1InnerRole
   */
  title: string
  /**
   *
   * @type {GetApplications200ResponseInnerNotes}
   * @memberof GetOpenings200Response1InnerRole
   */
  description?: GetApplications200ResponseInnerNotes
  /**
   *
   * @type {string}
   * @memberof GetOpenings200Response1InnerRole
   */
  workspaceId: string
  /**
   *
   * @type {any}
   * @memberof GetOpenings200Response1InnerRole
   */
  deletedAt?: any | null
}

/**
 * Check if a given object implements the GetOpenings200Response1InnerRole interface.
 */
export function instanceOfGetOpenings200Response1InnerRole(
  value: object,
): boolean {
  let isInstance = true
  isInstance = isInstance && "id" in value
  isInstance = isInstance && "updatedAt" in value
  isInstance = isInstance && "title" in value
  isInstance = isInstance && "workspaceId" in value

  return isInstance
}

export function GetOpenings200Response1InnerRoleFromJSON(
  json: any,
): GetOpenings200Response1InnerRole {
  return GetOpenings200Response1InnerRoleFromJSONTyped(json, false)
}

export function GetOpenings200Response1InnerRoleFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetOpenings200Response1InnerRole {
  if (json === undefined || json === null) {
    return json
  }
  return {
    ...json,
    id: json["id"],
    updatedAt: new Date(json["updatedAt"]),
    createdAt: !exists(json, "createdAt")
      ? undefined
      : new Date(json["createdAt"]),
    title: json["title"],
    description: !exists(json, "description")
      ? undefined
      : GetApplications200ResponseInnerNotesFromJSON(json["description"]),
    workspaceId: json["workspaceId"],
    deletedAt: !exists(json, "deletedAt") ? undefined : json["deletedAt"],
  }
}

export function GetOpenings200Response1InnerRoleToJSON(
  value?: GetOpenings200Response1InnerRole | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    ...value,
    id: value.id,
    updatedAt: value.updatedAt.toISOString(),
    createdAt:
      value.createdAt === undefined ? undefined : value.createdAt.toISOString(),
    title: value.title,
    description: GetApplications200ResponseInnerNotesToJSON(value.description),
    workspaceId: value.workspaceId,
    deletedAt: value.deletedAt,
  }
}
