/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
import type { GetApplications200ResponseInnerNotes } from "./GetApplications200ResponseInnerNotes"
import {
  GetApplications200ResponseInnerNotesFromJSON,
  GetApplications200ResponseInnerNotesFromJSONTyped,
  GetApplications200ResponseInnerNotesToJSON,
} from "./GetApplications200ResponseInnerNotes"
import type { GetOpening200Response1Form } from "./GetOpening200Response1Form"
import {
  GetOpening200Response1FormFromJSON,
  GetOpening200Response1FormFromJSONTyped,
  GetOpening200Response1FormToJSON,
} from "./GetOpening200Response1Form"
import type { GetOpenings200Response1InnerRole } from "./GetOpenings200Response1InnerRole"
import {
  GetOpenings200Response1InnerRoleFromJSON,
  GetOpenings200Response1InnerRoleFromJSONTyped,
  GetOpenings200Response1InnerRoleToJSON,
} from "./GetOpenings200Response1InnerRole"

/**
 *
 * @export
 * @interface GetOpening200Response2Opening
 */
export interface GetOpening200Response2Opening {
  [key: string]: any | any
  /**
   *
   * @type {string}
   * @memberof GetOpening200Response2Opening
   */
  id: string
  /**
   *
   * @type {Date}
   * @memberof GetOpening200Response2Opening
   */
  updatedAt: Date
  /**
   *
   * @type {Date}
   * @memberof GetOpening200Response2Opening
   */
  createdAt: Date
  /**
   *
   * @type {string}
   * @memberof GetOpening200Response2Opening
   */
  title: string
  /**
   *
   * @type {GetApplications200ResponseInnerNotes}
   * @memberof GetOpening200Response2Opening
   */
  description?: GetApplications200ResponseInnerNotes
  /**
   *
   * @type {string}
   * @memberof GetOpening200Response2Opening
   */
  workspaceId: string
  /**
   *
   * @type {string}
   * @memberof GetOpening200Response2Opening
   */
  roleId: string
  /**
   *
   * @type {any}
   * @memberof GetOpening200Response2Opening
   */
  formId?: any | null
  /**
   *
   * @type {string}
   * @memberof GetOpening200Response2Opening
   */
  workflowId: string
  /**
   *
   * @type {string}
   * @memberof GetOpening200Response2Opening
   */
  status?: GetOpening200Response2OpeningStatusEnum
  /**
   *
   * @type {any}
   * @memberof GetOpening200Response2Opening
   */
  deletedAt?: any | null
  /**
   *
   * @type {GetOpening200Response1Form}
   * @memberof GetOpening200Response2Opening
   */
  form: GetOpening200Response1Form
  /**
   *
   * @type {GetOpenings200Response1InnerRole}
   * @memberof GetOpening200Response2Opening
   */
  role: GetOpenings200Response1InnerRole
}

/**
 * @export
 * @enum {string}
 */
export enum GetOpening200Response2OpeningStatusEnum {
  Published = "Published",
  Draft = "Draft",
}

/**
 * Check if a given object implements the GetOpening200Response2Opening interface.
 */
export function instanceOfGetOpening200Response2Opening(
  value: object,
): boolean {
  let isInstance = true
  isInstance = isInstance && "id" in value
  isInstance = isInstance && "updatedAt" in value
  isInstance = isInstance && "createdAt" in value
  isInstance = isInstance && "title" in value
  isInstance = isInstance && "workspaceId" in value
  isInstance = isInstance && "roleId" in value
  isInstance = isInstance && "workflowId" in value
  isInstance = isInstance && "form" in value
  isInstance = isInstance && "role" in value

  return isInstance
}

export function GetOpening200Response2OpeningFromJSON(
  json: any,
): GetOpening200Response2Opening {
  return GetOpening200Response2OpeningFromJSONTyped(json, false)
}

export function GetOpening200Response2OpeningFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetOpening200Response2Opening {
  if (json === undefined || json === null) {
    return json
  }
  return {
    ...json,
    id: json["id"],
    updatedAt: new Date(json["updatedAt"]),
    createdAt: new Date(json["createdAt"]),
    title: json["title"],
    description: !exists(json, "description")
      ? undefined
      : GetApplications200ResponseInnerNotesFromJSON(json["description"]),
    workspaceId: json["workspaceId"],
    roleId: json["roleId"],
    formId: !exists(json, "formId") ? undefined : json["formId"],
    workflowId: json["workflowId"],
    status: !exists(json, "status") ? undefined : json["status"],
    deletedAt: !exists(json, "deletedAt") ? undefined : json["deletedAt"],
    form: GetOpening200Response1FormFromJSON(json["form"]),
    role: GetOpenings200Response1InnerRoleFromJSON(json["role"]),
  }
}

export function GetOpening200Response2OpeningToJSON(
  value?: GetOpening200Response2Opening | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    ...value,
    id: value.id,
    updatedAt: value.updatedAt.toISOString(),
    createdAt: value.createdAt.toISOString(),
    title: value.title,
    description: GetApplications200ResponseInnerNotesToJSON(value.description),
    workspaceId: value.workspaceId,
    roleId: value.roleId,
    formId: value.formId,
    workflowId: value.workflowId,
    status: value.status,
    deletedAt: value.deletedAt,
    form: GetOpening200Response1FormToJSON(value.form),
    role: GetOpenings200Response1InnerRoleToJSON(value.role),
  }
}
