/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
/**
 *
 * @export
 * @interface GetOpenings500Response
 */
export interface GetOpenings500Response {
  /**
   *
   * @type {string}
   * @memberof GetOpenings500Response
   */
  message?: string
}

/**
 * Check if a given object implements the GetOpenings500Response interface.
 */
export function instanceOfGetOpenings500Response(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function GetOpenings500ResponseFromJSON(
  json: any,
): GetOpenings500Response {
  return GetOpenings500ResponseFromJSONTyped(json, false)
}

export function GetOpenings500ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetOpenings500Response {
  if (json === undefined || json === null) {
    return json
  }
  return {
    message: !exists(json, "message") ? undefined : json["message"],
  }
}

export function GetOpenings500ResponseToJSON(
  value?: GetOpenings500Response | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    message: value.message,
  }
}
