/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetApplications200ResponseInnerNotes } from './GetApplications200ResponseInnerNotes';
import {
    GetApplications200ResponseInnerNotesFromJSON,
    GetApplications200ResponseInnerNotesFromJSONTyped,
    GetApplications200ResponseInnerNotesToJSON,
} from './GetApplications200ResponseInnerNotes';

/**
 * 
 * @export
 * @interface GetOpenings200ResponseInnerRole
 */
export interface GetOpenings200ResponseInnerRole {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof GetOpenings200ResponseInnerRole
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof GetOpenings200ResponseInnerRole
     */
    updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetOpenings200ResponseInnerRole
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof GetOpenings200ResponseInnerRole
     */
    title: string;
    /**
     * 
     * @type {GetApplications200ResponseInnerNotes}
     * @memberof GetOpenings200ResponseInnerRole
     */
    description?: GetApplications200ResponseInnerNotes;
    /**
     * 
     * @type {string}
     * @memberof GetOpenings200ResponseInnerRole
     */
    workspaceId: string;
    /**
     * 
     * @type {any}
     * @memberof GetOpenings200ResponseInnerRole
     */
    deletedAt?: any | null;
}

/**
 * Check if a given object implements the GetOpenings200ResponseInnerRole interface.
 */
export function instanceOfGetOpenings200ResponseInnerRole(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "updatedAt" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "workspaceId" in value;

    return isInstance;
}

export function GetOpenings200ResponseInnerRoleFromJSON(json: any): GetOpenings200ResponseInnerRole {
    return GetOpenings200ResponseInnerRoleFromJSONTyped(json, false);
}

export function GetOpenings200ResponseInnerRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOpenings200ResponseInnerRole {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'updatedAt': (new Date(json['updatedAt'])),
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'title': json['title'],
        'description': !exists(json, 'description') ? undefined : GetApplications200ResponseInnerNotesFromJSON(json['description']),
        'workspaceId': json['workspaceId'],
        'deletedAt': !exists(json, 'deletedAt') ? undefined : json['deletedAt'],
    };
}

export function GetOpenings200ResponseInnerRoleToJSON(value?: GetOpenings200ResponseInnerRole | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
            ...value,
        'id': value.id,
        'updatedAt': (value.updatedAt.toISOString()),
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'title': value.title,
        'description': GetApplications200ResponseInnerNotesToJSON(value.description),
        'workspaceId': value.workspaceId,
        'deletedAt': value.deletedAt,
    };
}

