/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
import type { GetOpenings200ResponseDataInner } from "./GetOpenings200ResponseDataInner"
import {
  GetOpenings200ResponseDataInnerFromJSON,
  GetOpenings200ResponseDataInnerFromJSONTyped,
  GetOpenings200ResponseDataInnerToJSON,
} from "./GetOpenings200ResponseDataInner"
import type { GetOpenings200ResponseInner } from "./GetOpenings200ResponseInner"
import {
  GetOpenings200ResponseInnerFromJSON,
  GetOpenings200ResponseInnerFromJSONTyped,
  GetOpenings200ResponseInnerToJSON,
} from "./GetOpenings200ResponseInner"

/**
 *
 * @export
 * @interface GetOpenings200Response
 */
export interface GetOpenings200Response {
  /**
   *
   * @type {Array<GetOpenings200ResponseDataInner>}
   * @memberof GetOpenings200Response
   */
  data?: Array<GetOpenings200ResponseDataInner>
  /**
   *
   * @type {Array<GetOpenings200ResponseInner>}
   * @memberof GetOpenings200Response
   */
  availableFilters?: Array<GetOpenings200ResponseInner>
}

/**
 * Check if a given object implements the GetOpenings200Response interface.
 */
export function instanceOfGetOpenings200Response(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function GetOpenings200ResponseFromJSON(
  json: any,
): GetOpenings200Response {
  return GetOpenings200ResponseFromJSONTyped(json, false)
}

export function GetOpenings200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetOpenings200Response {
  if (json === undefined || json === null) {
    return json
  }
  return {
    data: !exists(json, "data")
      ? undefined
      : (json["data"] as Array<any>).map(
          GetOpenings200ResponseDataInnerFromJSON,
        ),
    availableFilters: !exists(json, "availableFilters")
      ? undefined
      : (json["availableFilters"] as Array<any>).map(
          GetOpenings200ResponseInnerFromJSON,
        ),
  }
}

export function GetOpenings200ResponseToJSON(
  value?: GetOpenings200Response | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    data:
      value.data === undefined
        ? undefined
        : (value.data as Array<any>).map(GetOpenings200ResponseDataInnerToJSON),
    availableFilters:
      value.availableFilters === undefined
        ? undefined
        : (value.availableFilters as Array<any>).map(
            GetOpenings200ResponseInnerToJSON,
          ),
  }
}
