/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
import type { GetPermissions200ResponseInnerCount } from "./GetPermissions200ResponseInnerCount"
import {
  GetPermissions200ResponseInnerCountFromJSON,
  GetPermissions200ResponseInnerCountFromJSONTyped,
  GetPermissions200ResponseInnerCountToJSON,
} from "./GetPermissions200ResponseInnerCount"

/**
 *
 * @export
 * @interface GetPermissions200ResponseInner
 */
export interface GetPermissions200ResponseInner {
  /**
   *
   * @type {string}
   * @memberof GetPermissions200ResponseInner
   */
  id: string
  /**
   *
   * @type {Date}
   * @memberof GetPermissions200ResponseInner
   */
  updatedAt: Date
  /**
   *
   * @type {Date}
   * @memberof GetPermissions200ResponseInner
   */
  createdAt: Date
  /**
   *
   * @type {string}
   * @memberof GetPermissions200ResponseInner
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof GetPermissions200ResponseInner
   */
  description?: string
  /**
   *
   * @type {any}
   * @memberof GetPermissions200ResponseInner
   */
  creatorId?: any | null
  /**
   *
   * @type {string}
   * @memberof GetPermissions200ResponseInner
   */
  workspaceId: string
  /**
   *
   * @type {any}
   * @memberof GetPermissions200ResponseInner
   */
  filter?: any | null
  /**
   *
   * @type {Array<string>}
   * @memberof GetPermissions200ResponseInner
   */
  permissions?: Array<string>
  /**
   *
   * @type {GetPermissions200ResponseInnerCount}
   * @memberof GetPermissions200ResponseInner
   */
  count: GetPermissions200ResponseInnerCount
}

/**
 * Check if a given object implements the GetPermissions200ResponseInner interface.
 */
export function instanceOfGetPermissions200ResponseInner(
  value: object,
): boolean {
  let isInstance = true
  isInstance = isInstance && "id" in value
  isInstance = isInstance && "updatedAt" in value
  isInstance = isInstance && "createdAt" in value
  isInstance = isInstance && "name" in value
  isInstance = isInstance && "workspaceId" in value
  isInstance = isInstance && "count" in value

  return isInstance
}

export function GetPermissions200ResponseInnerFromJSON(
  json: any,
): GetPermissions200ResponseInner {
  return GetPermissions200ResponseInnerFromJSONTyped(json, false)
}

export function GetPermissions200ResponseInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetPermissions200ResponseInner {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: json["id"],
    updatedAt: new Date(json["updatedAt"]),
    createdAt: new Date(json["createdAt"]),
    name: json["name"],
    description: !exists(json, "description") ? undefined : json["description"],
    creatorId: !exists(json, "creatorId") ? undefined : json["creatorId"],
    workspaceId: json["workspaceId"],
    filter: !exists(json, "filter") ? undefined : json["filter"],
    permissions: !exists(json, "permissions") ? undefined : json["permissions"],
    count: GetPermissions200ResponseInnerCountFromJSON(json["_count"]),
  }
}

export function GetPermissions200ResponseInnerToJSON(
  value?: GetPermissions200ResponseInner | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id,
    updatedAt: value.updatedAt.toISOString(),
    createdAt: value.createdAt.toISOString(),
    name: value.name,
    description: value.description,
    creatorId: value.creatorId,
    workspaceId: value.workspaceId,
    filter: value.filter,
    permissions: value.permissions,
    _count: GetPermissions200ResponseInnerCountToJSON(value.count),
  }
}
