/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetReviews200ResponseInnerApplication } from './GetReviews200ResponseInnerApplication';
import {
    GetReviews200ResponseInnerApplicationFromJSON,
    GetReviews200ResponseInnerApplicationFromJSONTyped,
    GetReviews200ResponseInnerApplicationToJSON,
} from './GetReviews200ResponseInnerApplication';

/**
 * 
 * @export
 * @interface GetReviews200ResponseInner
 */
export interface GetReviews200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof GetReviews200ResponseInner
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof GetReviews200ResponseInner
     */
    updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetReviews200ResponseInner
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof GetReviews200ResponseInner
     */
    workspaceId: string;
    /**
     * 
     * @type {string}
     * @memberof GetReviews200ResponseInner
     */
    applicationId: string;
    /**
     * 
     * @type {string}
     * @memberof GetReviews200ResponseInner
     */
    authorId: string;
    /**
     * 
     * @type {any}
     * @memberof GetReviews200ResponseInner
     */
    responses: any | null;
    /**
     * 
     * @type {string}
     * @memberof GetReviews200ResponseInner
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof GetReviews200ResponseInner
     */
    status?: GetReviews200ResponseInnerStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof GetReviews200ResponseInner
     */
    source: GetReviews200ResponseInnerSourceEnum;
    /**
     * 
     * @type {string}
     * @memberof GetReviews200ResponseInner
     */
    sourceId: string;
    /**
     * 
     * @type {any}
     * @memberof GetReviews200ResponseInner
     */
    formId?: any | null;
    /**
     * 
     * @type {GetReviews200ResponseInnerApplication}
     * @memberof GetReviews200ResponseInner
     */
    application?: GetReviews200ResponseInnerApplication;
}

/**
* @export
* @enum {string}
*/
export enum GetReviews200ResponseInnerStatusEnum {
    Pending = 'Pending',
    Approved = 'Approved',
    Rejected = 'Rejected'
}
/**
* @export
* @enum {string}
*/
export enum GetReviews200ResponseInnerSourceEnum {
    Profile = 'Profile',
    Candidate = 'Candidate'
}


/**
 * Check if a given object implements the GetReviews200ResponseInner interface.
 */
export function instanceOfGetReviews200ResponseInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "updatedAt" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "workspaceId" in value;
    isInstance = isInstance && "applicationId" in value;
    isInstance = isInstance && "authorId" in value;
    isInstance = isInstance && "responses" in value;
    isInstance = isInstance && "source" in value;
    isInstance = isInstance && "sourceId" in value;

    return isInstance;
}

export function GetReviews200ResponseInnerFromJSON(json: any): GetReviews200ResponseInner {
    return GetReviews200ResponseInnerFromJSONTyped(json, false);
}

export function GetReviews200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetReviews200ResponseInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'updatedAt': (new Date(json['updatedAt'])),
        'createdAt': (new Date(json['createdAt'])),
        'workspaceId': json['workspaceId'],
        'applicationId': json['applicationId'],
        'authorId': json['authorId'],
        'responses': json['responses'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'source': json['source'],
        'sourceId': json['sourceId'],
        'formId': !exists(json, 'formId') ? undefined : json['formId'],
        'application': !exists(json, 'application') ? undefined : GetReviews200ResponseInnerApplicationFromJSON(json['application']),
    };
}

export function GetReviews200ResponseInnerToJSON(value?: GetReviews200ResponseInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'updatedAt': (value.updatedAt.toISOString()),
        'createdAt': (value.createdAt.toISOString()),
        'workspaceId': value.workspaceId,
        'applicationId': value.applicationId,
        'authorId': value.authorId,
        'responses': value.responses,
        'description': value.description,
        'status': value.status,
        'source': value.source,
        'sourceId': value.sourceId,
        'formId': value.formId,
        'application': GetReviews200ResponseInnerApplicationToJSON(value.application),
    };
}

