/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetOpening200ResponseForm } from './GetOpening200ResponseForm';
import {
    GetOpening200ResponseFormFromJSON,
    GetOpening200ResponseFormFromJSONTyped,
    GetOpening200ResponseFormToJSON,
} from './GetOpening200ResponseForm';
import type { GetReview200ResponseApplication } from './GetReview200ResponseApplication';
import {
    GetReview200ResponseApplicationFromJSON,
    GetReview200ResponseApplicationFromJSONTyped,
    GetReview200ResponseApplicationToJSON,
} from './GetReview200ResponseApplication';

/**
 * 
 * @export
 * @interface GetReview200Response
 */
export interface GetReview200Response {
    /**
     * 
     * @type {string}
     * @memberof GetReview200Response
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof GetReview200Response
     */
    updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetReview200Response
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof GetReview200Response
     */
    workspaceId: string;
    /**
     * 
     * @type {string}
     * @memberof GetReview200Response
     */
    applicationId: string;
    /**
     * 
     * @type {string}
     * @memberof GetReview200Response
     */
    authorId: string;
    /**
     * 
     * @type {any}
     * @memberof GetReview200Response
     */
    responses: any | null;
    /**
     * 
     * @type {string}
     * @memberof GetReview200Response
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof GetReview200Response
     */
    status?: GetReview200ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof GetReview200Response
     */
    source: GetReview200ResponseSourceEnum;
    /**
     * 
     * @type {string}
     * @memberof GetReview200Response
     */
    sourceId: string;
    /**
     * 
     * @type {any}
     * @memberof GetReview200Response
     */
    formId?: any | null;
    /**
     * 
     * @type {GetReview200ResponseApplication}
     * @memberof GetReview200Response
     */
    application?: GetReview200ResponseApplication;
    /**
     * 
     * @type {GetOpening200ResponseForm}
     * @memberof GetReview200Response
     */
    form?: GetOpening200ResponseForm;
    /**
     * 
     * @type {string}
     * @memberof GetReview200Response
     */
    name?: string;
}

/**
* @export
* @enum {string}
*/
export enum GetReview200ResponseStatusEnum {
    Pending = 'Pending',
    Approved = 'Approved',
    Rejected = 'Rejected'
}
/**
* @export
* @enum {string}
*/
export enum GetReview200ResponseSourceEnum {
    Profile = 'Profile',
    Candidate = 'Candidate'
}


/**
 * Check if a given object implements the GetReview200Response interface.
 */
export function instanceOfGetReview200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "updatedAt" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "workspaceId" in value;
    isInstance = isInstance && "applicationId" in value;
    isInstance = isInstance && "authorId" in value;
    isInstance = isInstance && "responses" in value;
    isInstance = isInstance && "source" in value;
    isInstance = isInstance && "sourceId" in value;

    return isInstance;
}

export function GetReview200ResponseFromJSON(json: any): GetReview200Response {
    return GetReview200ResponseFromJSONTyped(json, false);
}

export function GetReview200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetReview200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'updatedAt': (new Date(json['updatedAt'])),
        'createdAt': (new Date(json['createdAt'])),
        'workspaceId': json['workspaceId'],
        'applicationId': json['applicationId'],
        'authorId': json['authorId'],
        'responses': json['responses'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'source': json['source'],
        'sourceId': json['sourceId'],
        'formId': !exists(json, 'formId') ? undefined : json['formId'],
        'application': !exists(json, 'application') ? undefined : GetReview200ResponseApplicationFromJSON(json['application']),
        'form': !exists(json, 'form') ? undefined : GetOpening200ResponseFormFromJSON(json['form']),
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function GetReview200ResponseToJSON(value?: GetReview200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'updatedAt': (value.updatedAt.toISOString()),
        'createdAt': (value.createdAt.toISOString()),
        'workspaceId': value.workspaceId,
        'applicationId': value.applicationId,
        'authorId': value.authorId,
        'responses': value.responses,
        'description': value.description,
        'status': value.status,
        'source': value.source,
        'sourceId': value.sourceId,
        'formId': value.formId,
        'application': GetReview200ResponseApplicationToJSON(value.application),
        'form': GetOpening200ResponseFormToJSON(value.form),
        'name': value.name,
    };
}

