/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetApplicationStatuses200ResponseInner } from './GetApplicationStatuses200ResponseInner';
import {
    GetApplicationStatuses200ResponseInnerFromJSON,
    GetApplicationStatuses200ResponseInnerFromJSONTyped,
    GetApplicationStatuses200ResponseInnerToJSON,
} from './GetApplicationStatuses200ResponseInner';
import type { GetApplications200ResponseInnerCandidate } from './GetApplications200ResponseInnerCandidate';
import {
    GetApplications200ResponseInnerCandidateFromJSON,
    GetApplications200ResponseInnerCandidateFromJSONTyped,
    GetApplications200ResponseInnerCandidateToJSON,
} from './GetApplications200ResponseInnerCandidate';
import type { GetApplications200ResponseInnerNotes } from './GetApplications200ResponseInnerNotes';
import {
    GetApplications200ResponseInnerNotesFromJSON,
    GetApplications200ResponseInnerNotesFromJSONTyped,
    GetApplications200ResponseInnerNotesToJSON,
} from './GetApplications200ResponseInnerNotes';

/**
 * 
 * @export
 * @interface GetReview200ResponseApplication
 */
export interface GetReview200ResponseApplication {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof GetReview200ResponseApplication
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof GetReview200ResponseApplication
     */
    updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetReview200ResponseApplication
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof GetReview200ResponseApplication
     */
    resumeLink: string;
    /**
     * 
     * @type {string}
     * @memberof GetReview200ResponseApplication
     */
    resumeText: string;
    /**
     * 
     * @type {any}
     * @memberof GetReview200ResponseApplication
     */
    resumeData?: any | null;
    /**
     * 
     * @type {string}
     * @memberof GetReview200ResponseApplication
     */
    workspaceId: string;
    /**
     * 
     * @type {string}
     * @memberof GetReview200ResponseApplication
     */
    openingId: string;
    /**
     * 
     * @type {string}
     * @memberof GetReview200ResponseApplication
     */
    candidateId: string;
    /**
     * 
     * @type {string}
     * @memberof GetReview200ResponseApplication
     */
    creatorId?: string;
    /**
     * 
     * @type {any}
     * @memberof GetReview200ResponseApplication
     */
    statusId?: any | null;
    /**
     * 
     * @type {number}
     * @memberof GetReview200ResponseApplication
     */
    numberInWorkspace: number;
    /**
     * 
     * @type {GetApplications200ResponseInnerNotes}
     * @memberof GetReview200ResponseApplication
     */
    notes?: GetApplications200ResponseInnerNotes;
    /**
     * [FormResponses]
     * @type {any}
     * @memberof GetReview200ResponseApplication
     */
    responses: any | null;
    /**
     * 
     * @type {any}
     * @memberof GetReview200ResponseApplication
     */
    deletedAt?: any | null;
    /**
     * 
     * @type {GetApplications200ResponseInnerCandidate}
     * @memberof GetReview200ResponseApplication
     */
    candidate: GetApplications200ResponseInnerCandidate;
    /**
     * 
     * @type {GetApplicationStatuses200ResponseInner}
     * @memberof GetReview200ResponseApplication
     */
    status: GetApplicationStatuses200ResponseInner;
}

/**
 * Check if a given object implements the GetReview200ResponseApplication interface.
 */
export function instanceOfGetReview200ResponseApplication(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "updatedAt" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "resumeLink" in value;
    isInstance = isInstance && "resumeText" in value;
    isInstance = isInstance && "workspaceId" in value;
    isInstance = isInstance && "openingId" in value;
    isInstance = isInstance && "candidateId" in value;
    isInstance = isInstance && "numberInWorkspace" in value;
    isInstance = isInstance && "responses" in value;
    isInstance = isInstance && "candidate" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function GetReview200ResponseApplicationFromJSON(json: any): GetReview200ResponseApplication {
    return GetReview200ResponseApplicationFromJSONTyped(json, false);
}

export function GetReview200ResponseApplicationFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetReview200ResponseApplication {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'updatedAt': (new Date(json['updatedAt'])),
        'createdAt': (new Date(json['createdAt'])),
        'resumeLink': json['resumeLink'],
        'resumeText': json['resumeText'],
        'resumeData': !exists(json, 'resumeData') ? undefined : json['resumeData'],
        'workspaceId': json['workspaceId'],
        'openingId': json['openingId'],
        'candidateId': json['candidateId'],
        'creatorId': !exists(json, 'creatorId') ? undefined : json['creatorId'],
        'statusId': !exists(json, 'statusId') ? undefined : json['statusId'],
        'numberInWorkspace': json['numberInWorkspace'],
        'notes': !exists(json, 'notes') ? undefined : GetApplications200ResponseInnerNotesFromJSON(json['notes']),
        'responses': json['responses'],
        'deletedAt': !exists(json, 'deletedAt') ? undefined : json['deletedAt'],
        'candidate': GetApplications200ResponseInnerCandidateFromJSON(json['candidate']),
        'status': GetApplicationStatuses200ResponseInnerFromJSON(json['status']),
    };
}

export function GetReview200ResponseApplicationToJSON(value?: GetReview200ResponseApplication | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
            ...value,
        'id': value.id,
        'updatedAt': (value.updatedAt.toISOString()),
        'createdAt': (value.createdAt.toISOString()),
        'resumeLink': value.resumeLink,
        'resumeText': value.resumeText,
        'resumeData': value.resumeData,
        'workspaceId': value.workspaceId,
        'openingId': value.openingId,
        'candidateId': value.candidateId,
        'creatorId': value.creatorId,
        'statusId': value.statusId,
        'numberInWorkspace': value.numberInWorkspace,
        'notes': GetApplications200ResponseInnerNotesToJSON(value.notes),
        'responses': value.responses,
        'deletedAt': value.deletedAt,
        'candidate': GetApplications200ResponseInnerCandidateToJSON(value.candidate),
        'status': GetApplicationStatuses200ResponseInnerToJSON(value.status),
    };
}

