/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateEmailAddress200Response } from './CreateEmailAddress200Response';
import {
    CreateEmailAddress200ResponseFromJSON,
    CreateEmailAddress200ResponseFromJSONTyped,
    CreateEmailAddress200ResponseToJSON,
} from './CreateEmailAddress200Response';

/**
 * 
 * @export
 * @interface GetWorkspaceAuthToken200ResponseMetaWorkspaceMembersInner
 */
export interface GetWorkspaceAuthToken200ResponseMetaWorkspaceMembersInner {
    /**
     * 
     * @type {string}
     * @memberof GetWorkspaceAuthToken200ResponseMetaWorkspaceMembersInner
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof GetWorkspaceAuthToken200ResponseMetaWorkspaceMembersInner
     */
    updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetWorkspaceAuthToken200ResponseMetaWorkspaceMembersInner
     */
    createdAt?: Date;
    /**
     * 
     * @type {any}
     * @memberof GetWorkspaceAuthToken200ResponseMetaWorkspaceMembersInner
     */
    displayName?: any | null;
    /**
     * 
     * @type {string}
     * @memberof GetWorkspaceAuthToken200ResponseMetaWorkspaceMembersInner
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof GetWorkspaceAuthToken200ResponseMetaWorkspaceMembersInner
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof GetWorkspaceAuthToken200ResponseMetaWorkspaceMembersInner
     */
    userId: string;
    /**
     * 
     * @type {any}
     * @memberof GetWorkspaceAuthToken200ResponseMetaWorkspaceMembersInner
     */
    pictureSlug?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GetWorkspaceAuthToken200ResponseMetaWorkspaceMembersInner
     */
    deactivated?: any | null;
    /**
     * 
     * @type {string}
     * @memberof GetWorkspaceAuthToken200ResponseMetaWorkspaceMembersInner
     */
    workspaceId: string;
    /**
     * 
     * @type {any}
     * @memberof GetWorkspaceAuthToken200ResponseMetaWorkspaceMembersInner
     */
    savedFolderId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof GetWorkspaceAuthToken200ResponseMetaWorkspaceMembersInner
     */
    savedId?: any | null;
    /**
     * 
     * @type {Array<CreateEmailAddress200Response>}
     * @memberof GetWorkspaceAuthToken200ResponseMetaWorkspaceMembersInner
     */
    emailAddresses: Array<CreateEmailAddress200Response>;
}

/**
 * Check if a given object implements the GetWorkspaceAuthToken200ResponseMetaWorkspaceMembersInner interface.
 */
export function instanceOfGetWorkspaceAuthToken200ResponseMetaWorkspaceMembersInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "updatedAt" in value;
    isInstance = isInstance && "firstName" in value;
    isInstance = isInstance && "lastName" in value;
    isInstance = isInstance && "userId" in value;
    isInstance = isInstance && "workspaceId" in value;
    isInstance = isInstance && "emailAddresses" in value;

    return isInstance;
}

export function GetWorkspaceAuthToken200ResponseMetaWorkspaceMembersInnerFromJSON(json: any): GetWorkspaceAuthToken200ResponseMetaWorkspaceMembersInner {
    return GetWorkspaceAuthToken200ResponseMetaWorkspaceMembersInnerFromJSONTyped(json, false);
}

export function GetWorkspaceAuthToken200ResponseMetaWorkspaceMembersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetWorkspaceAuthToken200ResponseMetaWorkspaceMembersInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'updatedAt': (new Date(json['updatedAt'])),
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'userId': json['userId'],
        'pictureSlug': !exists(json, 'pictureSlug') ? undefined : json['pictureSlug'],
        'deactivated': !exists(json, 'deactivated') ? undefined : json['deactivated'],
        'workspaceId': json['workspaceId'],
        'savedFolderId': !exists(json, 'savedFolderId') ? undefined : json['savedFolderId'],
        'savedId': !exists(json, 'savedId') ? undefined : json['savedId'],
        'emailAddresses': ((json['emailAddresses'] as Array<any>).map(CreateEmailAddress200ResponseFromJSON)),
    };
}

export function GetWorkspaceAuthToken200ResponseMetaWorkspaceMembersInnerToJSON(value?: GetWorkspaceAuthToken200ResponseMetaWorkspaceMembersInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'updatedAt': (value.updatedAt.toISOString()),
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'displayName': value.displayName,
        'firstName': value.firstName,
        'lastName': value.lastName,
        'userId': value.userId,
        'pictureSlug': value.pictureSlug,
        'deactivated': value.deactivated,
        'workspaceId': value.workspaceId,
        'savedFolderId': value.savedFolderId,
        'savedId': value.savedId,
        'emailAddresses': ((value.emailAddresses as Array<any>).map(CreateEmailAddress200ResponseToJSON)),
    };
}

