/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
/**
 *
 * @export
 * @interface GetWorkflows200ResponseInnerDefinition
 */
export interface GetWorkflows200ResponseInnerDefinition {
  /**
   *
   * @type {any}
   * @memberof GetWorkflows200ResponseInnerDefinition
   */
  graph: any | null
  /**
   *
   * @type {any}
   * @memberof GetWorkflows200ResponseInnerDefinition
   */
  config: any | null
  /**
   *
   * @type {number}
   * @memberof GetWorkflows200ResponseInnerDefinition
   */
  version: number
}

/**
 * Check if a given object implements the GetWorkflows200ResponseInnerDefinition interface.
 */
export function instanceOfGetWorkflows200ResponseInnerDefinition(
  value: object,
): boolean {
  let isInstance = true
  isInstance = isInstance && "graph" in value
  isInstance = isInstance && "config" in value
  isInstance = isInstance && "version" in value

  return isInstance
}

export function GetWorkflows200ResponseInnerDefinitionFromJSON(
  json: any,
): GetWorkflows200ResponseInnerDefinition {
  return GetWorkflows200ResponseInnerDefinitionFromJSONTyped(json, false)
}

export function GetWorkflows200ResponseInnerDefinitionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetWorkflows200ResponseInnerDefinition {
  if (json === undefined || json === null) {
    return json
  }
  return {
    graph: json["graph"],
    config: json["config"],
    version: json["version"],
  }
}

export function GetWorkflows200ResponseInnerDefinitionToJSON(
  value?: GetWorkflows200ResponseInnerDefinition | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    graph: value.graph,
    config: value.config,
    version: value.version,
  }
}
