/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetWorkspace200Response
 */
export interface GetWorkspace200Response {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof GetWorkspace200Response
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof GetWorkspace200Response
     */
    updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetWorkspace200Response
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof GetWorkspace200Response
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof GetWorkspace200Response
     */
    name: string;
    /**
     * 
     * @type {any}
     * @memberof GetWorkspace200Response
     */
    logoSlug?: any | null;
    /**
     * 
     * @type {string}
     * @memberof GetWorkspace200Response
     */
    creatorId: string;
    /**
     * 
     * @type {any}
     * @memberof GetWorkspace200Response
     */
    onboarding?: any | null;
}

/**
 * Check if a given object implements the GetWorkspace200Response interface.
 */
export function instanceOfGetWorkspace200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "updatedAt" in value;
    isInstance = isInstance && "url" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "creatorId" in value;

    return isInstance;
}

export function GetWorkspace200ResponseFromJSON(json: any): GetWorkspace200Response {
    return GetWorkspace200ResponseFromJSONTyped(json, false);
}

export function GetWorkspace200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetWorkspace200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'updatedAt': (new Date(json['updatedAt'])),
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'url': json['url'],
        'name': json['name'],
        'logoSlug': !exists(json, 'logoSlug') ? undefined : json['logoSlug'],
        'creatorId': json['creatorId'],
        'onboarding': !exists(json, 'onboarding') ? undefined : json['onboarding'],
    };
}

export function GetWorkspace200ResponseToJSON(value?: GetWorkspace200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
            ...value,
        'id': value.id,
        'updatedAt': (value.updatedAt.toISOString()),
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'url': value.url,
        'name': value.name,
        'logoSlug': value.logoSlug,
        'creatorId': value.creatorId,
        'onboarding': value.onboarding,
    };
}

