/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
/**
 *
 * @export
 * @interface StartOnboardingWorkflow201Response
 */
export interface StartOnboardingWorkflow201Response {
  /**
   *
   * @type {string}
   * @memberof StartOnboardingWorkflow201Response
   */
  message?: string
  /**
   *
   * @type {string}
   * @memberof StartOnboardingWorkflow201Response
   */
  workflowId?: string
}

/**
 * Check if a given object implements the StartOnboardingWorkflow201Response interface.
 */
export function instanceOfStartOnboardingWorkflow201Response(
  value: object,
): boolean {
  let isInstance = true

  return isInstance
}

export function StartOnboardingWorkflow201ResponseFromJSON(
  json: any,
): StartOnboardingWorkflow201Response {
  return StartOnboardingWorkflow201ResponseFromJSONTyped(json, false)
}

export function StartOnboardingWorkflow201ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): StartOnboardingWorkflow201Response {
  if (json === undefined || json === null) {
    return json
  }
  return {
    message: !exists(json, "message") ? undefined : json["message"],
    workflowId: !exists(json, "workflowId") ? undefined : json["workflowId"],
  }
}

export function StartOnboardingWorkflow201ResponseToJSON(
  value?: StartOnboardingWorkflow201Response | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    message: value.message,
    workflowId: value.workflowId,
  }
}
