/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
/**
 *
 * @export
 * @interface UpdateMeetingNoteRequest
 */
export interface UpdateMeetingNoteRequest {
  /**
   *
   * @type {string}
   * @memberof UpdateMeetingNoteRequest
   */
  content: string
}

/**
 * Check if a given object implements the UpdateMeetingNoteRequest interface.
 */
export function instanceOfUpdateMeetingNoteRequest(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && "content" in value

  return isInstance
}

export function UpdateMeetingNoteRequestFromJSON(
  json: any,
): UpdateMeetingNoteRequest {
  return UpdateMeetingNoteRequestFromJSONTyped(json, false)
}

export function UpdateMeetingNoteRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateMeetingNoteRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    content: json["content"],
  }
}

export function UpdateMeetingNoteRequestToJSON(
  value?: UpdateMeetingNoteRequest | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    content: value.content,
  }
}
