/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
/**
 *
 * @export
 * @interface UpdateOnboardingDataRequestDataTemplatesPages
 */
export interface UpdateOnboardingDataRequestDataTemplatesPages {
  /**
   *
   * @type {string}
   * @memberof UpdateOnboardingDataRequestDataTemplatesPages
   */
  careers?: string
  /**
   *
   * @type {string}
   * @memberof UpdateOnboardingDataRequestDataTemplatesPages
   */
  opening?: string
}

/**
 * Check if a given object implements the UpdateOnboardingDataRequestDataTemplatesPages interface.
 */
export function instanceOfUpdateOnboardingDataRequestDataTemplatesPages(
  value: object,
): boolean {
  let isInstance = true

  return isInstance
}

export function UpdateOnboardingDataRequestDataTemplatesPagesFromJSON(
  json: any,
): UpdateOnboardingDataRequestDataTemplatesPages {
  return UpdateOnboardingDataRequestDataTemplatesPagesFromJSONTyped(json, false)
}

export function UpdateOnboardingDataRequestDataTemplatesPagesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateOnboardingDataRequestDataTemplatesPages {
  if (json === undefined || json === null) {
    return json
  }
  return {
    careers: !exists(json, "careers") ? undefined : json["careers"],
    opening: !exists(json, "opening") ? undefined : json["opening"],
  }
}

export function UpdateOnboardingDataRequestDataTemplatesPagesToJSON(
  value?: UpdateOnboardingDataRequestDataTemplatesPages | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    careers: value.careers,
    opening: value.opening,
  }
}
