/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
import type { UpdateWorkflowRunStepRequestMeetingCompleted } from "./UpdateWorkflowRunStepRequestMeetingCompleted"
import {
  UpdateWorkflowRunStepRequestMeetingCompletedFromJSON,
  UpdateWorkflowRunStepRequestMeetingCompletedFromJSONTyped,
  UpdateWorkflowRunStepRequestMeetingCompletedToJSON,
} from "./UpdateWorkflowRunStepRequestMeetingCompleted"

/**
 *
 * @export
 * @interface UpdateWorkflowRunStepRequest
 */
export interface UpdateWorkflowRunStepRequest {
  /**
   *
   * @type {string}
   * @memberof UpdateWorkflowRunStepRequest
   */
  manualReviewApproval?: UpdateWorkflowRunStepRequestManualReviewApprovalEnum
  /**
   *
   * @type {UpdateWorkflowRunStepRequestMeetingCompleted}
   * @memberof UpdateWorkflowRunStepRequest
   */
  meetingCompleted?: UpdateWorkflowRunStepRequestMeetingCompleted
}

/**
 * @export
 * @enum {string}
 */
export enum UpdateWorkflowRunStepRequestManualReviewApprovalEnum {
  Approved = "Approved",
  Rejected = "Rejected",
}

/**
 * Check if a given object implements the UpdateWorkflowRunStepRequest interface.
 */
export function instanceOfUpdateWorkflowRunStepRequest(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function UpdateWorkflowRunStepRequestFromJSON(
  json: any,
): UpdateWorkflowRunStepRequest {
  return UpdateWorkflowRunStepRequestFromJSONTyped(json, false)
}

export function UpdateWorkflowRunStepRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateWorkflowRunStepRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    manualReviewApproval: !exists(json, "manualReviewApproval")
      ? undefined
      : json["manualReviewApproval"],
    meetingCompleted: !exists(json, "meetingCompleted")
      ? undefined
      : UpdateWorkflowRunStepRequestMeetingCompletedFromJSON(
          json["meetingCompleted"],
        ),
  }
}

export function UpdateWorkflowRunStepRequestToJSON(
  value?: UpdateWorkflowRunStepRequest | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    manualReviewApproval: value.manualReviewApproval,
    meetingCompleted: UpdateWorkflowRunStepRequestMeetingCompletedToJSON(
      value.meetingCompleted,
    ),
  }
}
