/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetApplications200ResponseInnerNotes } from './GetApplications200ResponseInnerNotes';
import {
    GetApplications200ResponseInnerNotesFromJSON,
    GetApplications200ResponseInnerNotesFromJSONTyped,
    GetApplications200ResponseInnerNotesToJSON,
} from './GetApplications200ResponseInnerNotes';

/**
 * 
 * @export
 * @interface UpdateARoleRequest
 */
export interface UpdateARoleRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateARoleRequest
     */
    title?: string;
    /**
     * 
     * @type {GetApplications200ResponseInnerNotes}
     * @memberof UpdateARoleRequest
     */
    description?: GetApplications200ResponseInnerNotes;
}

/**
 * Check if a given object implements the UpdateARoleRequest interface.
 */
export function instanceOfUpdateARoleRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateARoleRequestFromJSON(json: any): UpdateARoleRequest {
    return UpdateARoleRequestFromJSONTyped(json, false);
}

export function UpdateARoleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateARoleRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': !exists(json, 'title') ? undefined : json['title'],
        'description': !exists(json, 'description') ? undefined : GetApplications200ResponseInnerNotesFromJSON(json['description']),
    };
}

export function UpdateARoleRequestToJSON(value?: UpdateARoleRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'description': GetApplications200ResponseInnerNotesToJSON(value.description),
    };
}

