/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateApplicationRequest
 */
export interface UpdateApplicationRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateApplicationRequest
     */
    candidate?: string;
    /**
     * ID of the application status
     * @type {string}
     * @memberof UpdateApplicationRequest
     */
    statusId?: string;
}

/**
 * Check if a given object implements the UpdateApplicationRequest interface.
 */
export function instanceOfUpdateApplicationRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateApplicationRequestFromJSON(json: any): UpdateApplicationRequest {
    return UpdateApplicationRequestFromJSONTyped(json, false);
}

export function UpdateApplicationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateApplicationRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'candidate': !exists(json, 'candidate') ? undefined : json['candidate'],
        'statusId': !exists(json, 'statusId') ? undefined : json['statusId'],
    };
}

export function UpdateApplicationRequestToJSON(value?: UpdateApplicationRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'candidate': value.candidate,
        'statusId': value.statusId,
    };
}

