/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateApplicationStatusRequest
 */
export interface UpdateApplicationStatusRequest {
    /**
     * The name of the application status
     * @type {string}
     * @memberof UpdateApplicationStatusRequest
     */
    name?: string;
    /**
     * The category of the application status
     * @type {string}
     * @memberof UpdateApplicationStatusRequest
     */
    category?: UpdateApplicationStatusRequestCategoryEnum;
    /**
     * The color of the application status (hex code)
     * @type {string}
     * @memberof UpdateApplicationStatusRequest
     */
    color?: string;
}

/**
* @export
* @enum {string}
*/
export enum UpdateApplicationStatusRequestCategoryEnum {
    NotStarted = 'NotStarted',
    Started = 'Started',
    Completed = 'Completed',
    Rejected = 'Rejected'
}


/**
 * Check if a given object implements the UpdateApplicationStatusRequest interface.
 */
export function instanceOfUpdateApplicationStatusRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateApplicationStatusRequestFromJSON(json: any): UpdateApplicationStatusRequest {
    return UpdateApplicationStatusRequestFromJSONTyped(json, false);
}

export function UpdateApplicationStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateApplicationStatusRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'category': !exists(json, 'category') ? undefined : json['category'],
        'color': !exists(json, 'color') ? undefined : json['color'],
    };
}

export function UpdateApplicationStatusRequestToJSON(value?: UpdateApplicationStatusRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'category': value.category,
        'color': value.color,
    };
}

