/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UpdateWorkspaceRequestLogo } from './UpdateWorkspaceRequestLogo';
import {
    UpdateWorkspaceRequestLogoFromJSON,
    UpdateWorkspaceRequestLogoFromJSONTyped,
    UpdateWorkspaceRequestLogoToJSON,
} from './UpdateWorkspaceRequestLogo';

/**
 * 
 * @export
 * @interface UpdateProfileRequest
 */
export interface UpdateProfileRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateProfileRequest
     */
    displayName?: string;
    /**
     * 
     * @type {UpdateWorkspaceRequestLogo}
     * @memberof UpdateProfileRequest
     */
    picture?: UpdateWorkspaceRequestLogo;
}

/**
 * Check if a given object implements the UpdateProfileRequest interface.
 */
export function instanceOfUpdateProfileRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateProfileRequestFromJSON(json: any): UpdateProfileRequest {
    return UpdateProfileRequestFromJSONTyped(json, false);
}

export function UpdateProfileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProfileRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
        'picture': !exists(json, 'picture') ? undefined : UpdateWorkspaceRequestLogoFromJSON(json['picture']),
    };
}

export function UpdateProfileRequestToJSON(value?: UpdateProfileRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'displayName': value.displayName,
        'picture': UpdateWorkspaceRequestLogoToJSON(value.picture),
    };
}

