/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetApplications200ResponseInnerNotes } from './GetApplications200ResponseInnerNotes';
import {
    GetApplications200ResponseInnerNotesFromJSON,
    GetApplications200ResponseInnerNotesFromJSONTyped,
    GetApplications200ResponseInnerNotesToJSON,
} from './GetApplications200ResponseInnerNotes';

/**
 * 
 * @export
 * @interface UpdateEmailTemplateRequest
 */
export interface UpdateEmailTemplateRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateEmailTemplateRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateEmailTemplateRequest
     */
    subject?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateEmailTemplateRequest
     */
    description?: string;
    /**
     * 
     * @type {GetApplications200ResponseInnerNotes}
     * @memberof UpdateEmailTemplateRequest
     */
    content?: GetApplications200ResponseInnerNotes;
    /**
     * 
     * @type {string}
     * @memberof UpdateEmailTemplateRequest
     */
    emailType?: UpdateEmailTemplateRequestEmailTypeEnum;
}

/**
* @export
* @enum {string}
*/
export enum UpdateEmailTemplateRequestEmailTypeEnum {
    Application = 'Application'
}


/**
 * Check if a given object implements the UpdateEmailTemplateRequest interface.
 */
export function instanceOfUpdateEmailTemplateRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateEmailTemplateRequestFromJSON(json: any): UpdateEmailTemplateRequest {
    return UpdateEmailTemplateRequestFromJSONTyped(json, false);
}

export function UpdateEmailTemplateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateEmailTemplateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'subject': !exists(json, 'subject') ? undefined : json['subject'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'content': !exists(json, 'content') ? undefined : GetApplications200ResponseInnerNotesFromJSON(json['content']),
        'emailType': !exists(json, 'emailType') ? undefined : json['emailType'],
    };
}

export function UpdateEmailTemplateRequestToJSON(value?: UpdateEmailTemplateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'subject': value.subject,
        'description': value.description,
        'content': GetApplications200ResponseInnerNotesToJSON(value.content),
        'emailType': value.emailType,
    };
}

