/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateViewRequest
 */
export interface UpdateViewRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateViewRequest
     */
    name?: string;
    /**
     * 
     * @type {any}
     * @memberof UpdateViewRequest
     */
    config?: any | null;
}

/**
 * Check if a given object implements the UpdateViewRequest interface.
 */
export function instanceOfUpdateViewRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateViewRequestFromJSON(json: any): UpdateViewRequest {
    return UpdateViewRequestFromJSONTyped(json, false);
}

export function UpdateViewRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateViewRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'config': !exists(json, 'config') ? undefined : json['config'],
    };
}

export function UpdateViewRequestToJSON(value?: UpdateViewRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'config': value.config,
    };
}

