/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
import type { GetWorkflows200ResponseInnerDefinition } from "./GetWorkflows200ResponseInnerDefinition"
import {
  GetWorkflows200ResponseInnerDefinitionFromJSON,
  GetWorkflows200ResponseInnerDefinitionFromJSONTyped,
  GetWorkflows200ResponseInnerDefinitionToJSON,
} from "./GetWorkflows200ResponseInnerDefinition"

/**
 *
 * @export
 * @interface UpdateWorkflowRequest
 */
export interface UpdateWorkflowRequest {
  /**
   *
   * @type {string}
   * @memberof UpdateWorkflowRequest
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof UpdateWorkflowRequest
   */
  description?: string
  /**
   *
   * @type {GetWorkflows200ResponseInnerDefinition}
   * @memberof UpdateWorkflowRequest
   */
  definition?: GetWorkflows200ResponseInnerDefinition
  /**
   * The workflow status (Draft, Active, or Archived)
   * @type {string}
   * @memberof UpdateWorkflowRequest
   */
  status?: UpdateWorkflowRequestStatusEnum
}

/**
 * @export
 * @enum {string}
 */
export enum UpdateWorkflowRequestStatusEnum {
  Draft = "Draft",
  Active = "Active",
  Archived = "Archived",
}

/**
 * Check if a given object implements the UpdateWorkflowRequest interface.
 */
export function instanceOfUpdateWorkflowRequest(value: object): boolean {
  let isInstance = true

  return isInstance
}

export function UpdateWorkflowRequestFromJSON(
  json: any,
): UpdateWorkflowRequest {
  return UpdateWorkflowRequestFromJSONTyped(json, false)
}

export function UpdateWorkflowRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateWorkflowRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    name: !exists(json, "name") ? undefined : json["name"],
    description: !exists(json, "description") ? undefined : json["description"],
    definition: !exists(json, "definition")
      ? undefined
      : GetWorkflows200ResponseInnerDefinitionFromJSON(json["definition"]),
    status: !exists(json, "status") ? undefined : json["status"],
  }
}

export function UpdateWorkflowRequestToJSON(
  value?: UpdateWorkflowRequest | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    name: value.name,
    description: value.description,
    definition: GetWorkflows200ResponseInnerDefinitionToJSON(value.definition),
    status: value.status,
  }
}
