/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
import type { UpdateOnboardingDataRequestData } from "./UpdateOnboardingDataRequestData"
import {
  UpdateOnboardingDataRequestDataFromJSON,
  UpdateOnboardingDataRequestDataFromJSONTyped,
  UpdateOnboardingDataRequestDataToJSON,
} from "./UpdateOnboardingDataRequestData"

/**
 *
 * @export
 * @interface UpdateOnboardingDataRequest
 */
export interface UpdateOnboardingDataRequest {
  /**
   *
   * @type {UpdateOnboardingDataRequestData}
   * @memberof UpdateOnboardingDataRequest
   */
  data: UpdateOnboardingDataRequestData
}

/**
 * Check if a given object implements the UpdateOnboardingDataRequest interface.
 */
export function instanceOfUpdateOnboardingDataRequest(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && "data" in value

  return isInstance
}

export function UpdateOnboardingDataRequestFromJSON(
  json: any,
): UpdateOnboardingDataRequest {
  return UpdateOnboardingDataRequestFromJSONTyped(json, false)
}

export function UpdateOnboardingDataRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateOnboardingDataRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    data: UpdateOnboardingDataRequestDataFromJSON(json["data"]),
  }
}

export function UpdateOnboardingDataRequestToJSON(
  value?: UpdateOnboardingDataRequest | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    data: UpdateOnboardingDataRequestDataToJSON(value.data),
  }
}
