/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateSavedItemRequest
 */
export interface UpdateSavedItemRequest {
    /**
     * The name of the saved item
     * @type {string}
     * @memberof UpdateSavedItemRequest
     */
    name?: string;
    /**
     * The folder ID to move this saved item to (null to remove from folder)
     * @type {string}
     * @memberof UpdateSavedItemRequest
     */
    folderId?: string;
    /**
     * Whether this saved item is shared with the entire workspace
     * @type {boolean}
     * @memberof UpdateSavedItemRequest
     */
    isSharedWithWorkspace?: boolean;
    /**
     * Profile IDs to share this saved item with
     * @type {Array<string>}
     * @memberof UpdateSavedItemRequest
     */
    sharedWithProfileIds?: Array<string>;
}

/**
 * Check if a given object implements the UpdateSavedItemRequest interface.
 */
export function instanceOfUpdateSavedItemRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateSavedItemRequestFromJSON(json: any): UpdateSavedItemRequest {
    return UpdateSavedItemRequestFromJSONTyped(json, false);
}

export function UpdateSavedItemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSavedItemRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'folderId': !exists(json, 'folderId') ? undefined : json['folderId'],
        'isSharedWithWorkspace': !exists(json, 'isSharedWithWorkspace') ? undefined : json['isSharedWithWorkspace'],
        'sharedWithProfileIds': !exists(json, 'sharedWithProfileIds') ? undefined : json['sharedWithProfileIds'],
    };
}

export function UpdateSavedItemRequestToJSON(value?: UpdateSavedItemRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'folderId': value.folderId,
        'isSharedWithWorkspace': value.isSharedWithWorkspace,
        'sharedWithProfileIds': value.sharedWithProfileIds,
    };
}

