/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
import type { UpdateOnboardingDataRequestDataTemplatesEmailsInner } from "./UpdateOnboardingDataRequestDataTemplatesEmailsInner"
import {
  UpdateOnboardingDataRequestDataTemplatesEmailsInnerFromJSON,
  UpdateOnboardingDataRequestDataTemplatesEmailsInnerFromJSONTyped,
  UpdateOnboardingDataRequestDataTemplatesEmailsInnerToJSON,
} from "./UpdateOnboardingDataRequestDataTemplatesEmailsInner"
import type { UpdateOnboardingDataRequestDataTemplatesFormsInner } from "./UpdateOnboardingDataRequestDataTemplatesFormsInner"
import {
  UpdateOnboardingDataRequestDataTemplatesFormsInnerFromJSON,
  UpdateOnboardingDataRequestDataTemplatesFormsInnerFromJSONTyped,
  UpdateOnboardingDataRequestDataTemplatesFormsInnerToJSON,
} from "./UpdateOnboardingDataRequestDataTemplatesFormsInner"
import type { UpdateOnboardingDataRequestDataTemplatesPages } from "./UpdateOnboardingDataRequestDataTemplatesPages"
import {
  UpdateOnboardingDataRequestDataTemplatesPagesFromJSON,
  UpdateOnboardingDataRequestDataTemplatesPagesFromJSONTyped,
  UpdateOnboardingDataRequestDataTemplatesPagesToJSON,
} from "./UpdateOnboardingDataRequestDataTemplatesPages"

/**
 *
 * @export
 * @interface UpdateOnboardingDataRequestDataTemplates
 */
export interface UpdateOnboardingDataRequestDataTemplates {
  /**
   *
   * @type {UpdateOnboardingDataRequestDataTemplatesPages}
   * @memberof UpdateOnboardingDataRequestDataTemplates
   */
  pages?: UpdateOnboardingDataRequestDataTemplatesPages
  /**
   *
   * @type {Array<UpdateOnboardingDataRequestDataTemplatesFormsInner>}
   * @memberof UpdateOnboardingDataRequestDataTemplates
   */
  forms?: Array<UpdateOnboardingDataRequestDataTemplatesFormsInner>
  /**
   *
   * @type {Array<UpdateOnboardingDataRequestDataTemplatesEmailsInner>}
   * @memberof UpdateOnboardingDataRequestDataTemplates
   */
  emails?: Array<UpdateOnboardingDataRequestDataTemplatesEmailsInner>
}

/**
 * Check if a given object implements the UpdateOnboardingDataRequestDataTemplates interface.
 */
export function instanceOfUpdateOnboardingDataRequestDataTemplates(
  value: object,
): boolean {
  let isInstance = true

  return isInstance
}

export function UpdateOnboardingDataRequestDataTemplatesFromJSON(
  json: any,
): UpdateOnboardingDataRequestDataTemplates {
  return UpdateOnboardingDataRequestDataTemplatesFromJSONTyped(json, false)
}

export function UpdateOnboardingDataRequestDataTemplatesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateOnboardingDataRequestDataTemplates {
  if (json === undefined || json === null) {
    return json
  }
  return {
    pages: !exists(json, "pages")
      ? undefined
      : UpdateOnboardingDataRequestDataTemplatesPagesFromJSON(json["pages"]),
    forms: !exists(json, "forms")
      ? undefined
      : (json["forms"] as Array<any>).map(
          UpdateOnboardingDataRequestDataTemplatesFormsInnerFromJSON,
        ),
    emails: !exists(json, "emails")
      ? undefined
      : (json["emails"] as Array<any>).map(
          UpdateOnboardingDataRequestDataTemplatesEmailsInnerFromJSON,
        ),
  }
}

export function UpdateOnboardingDataRequestDataTemplatesToJSON(
  value?: UpdateOnboardingDataRequestDataTemplates | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    pages: UpdateOnboardingDataRequestDataTemplatesPagesToJSON(value.pages),
    forms:
      value.forms === undefined
        ? undefined
        : (value.forms as Array<any>).map(
            UpdateOnboardingDataRequestDataTemplatesFormsInnerToJSON,
          ),
    emails:
      value.emails === undefined
        ? undefined
        : (value.emails as Array<any>).map(
            UpdateOnboardingDataRequestDataTemplatesEmailsInnerToJSON,
          ),
  }
}
