/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpsertListingThemeRequest
 */
export interface UpsertListingThemeRequest {
    /**
     * 
     * @type {string}
     * @memberof UpsertListingThemeRequest
     */
    name: string;
    /**
     * 
     * @type {any}
     * @memberof UpsertListingThemeRequest
     */
    openingConfig?: any | null;
    /**
     * 
     * @type {any}
     * @memberof UpsertListingThemeRequest
     */
    openingsConfig?: any | null;
}

/**
 * Check if a given object implements the UpsertListingThemeRequest interface.
 */
export function instanceOfUpsertListingThemeRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function UpsertListingThemeRequestFromJSON(json: any): UpsertListingThemeRequest {
    return UpsertListingThemeRequestFromJSONTyped(json, false);
}

export function UpsertListingThemeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpsertListingThemeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'openingConfig': !exists(json, 'openingConfig') ? undefined : json['openingConfig'],
        'openingsConfig': !exists(json, 'openingsConfig') ? undefined : json['openingsConfig'],
    };
}

export function UpsertListingThemeRequestToJSON(value?: UpsertListingThemeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'openingConfig': value.openingConfig,
        'openingsConfig': value.openingsConfig,
    };
}

