/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyAuthentication200ResponseMeta
 */
export interface VerifyAuthentication200ResponseMeta {
    /**
     * 
     * @type {string}
     * @memberof VerifyAuthentication200ResponseMeta
     */
    email: string;
}

/**
 * Check if a given object implements the VerifyAuthentication200ResponseMeta interface.
 */
export function instanceOfVerifyAuthentication200ResponseMeta(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;

    return isInstance;
}

export function VerifyAuthentication200ResponseMetaFromJSON(json: any): VerifyAuthentication200ResponseMeta {
    return VerifyAuthentication200ResponseMetaFromJSONTyped(json, false);
}

export function VerifyAuthentication200ResponseMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyAuthentication200ResponseMeta {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function VerifyAuthentication200ResponseMetaToJSON(value?: VerifyAuthentication200ResponseMeta | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}

