/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
import type { WorkspaceMeetingTemplateGet201ResponseTemplate } from "./WorkspaceMeetingTemplateGet201ResponseTemplate"
import {
  WorkspaceMeetingTemplateGet201ResponseTemplateFromJSON,
  WorkspaceMeetingTemplateGet201ResponseTemplateFromJSONTyped,
  WorkspaceMeetingTemplateGet201ResponseTemplateToJSON,
} from "./WorkspaceMeetingTemplateGet201ResponseTemplate"

/**
 *
 * @export
 * @interface WorkspaceMeetingTemplateGet201Response
 */
export interface WorkspaceMeetingTemplateGet201Response {
  /**
   *
   * @type {WorkspaceMeetingTemplateGet201ResponseTemplate}
   * @memberof WorkspaceMeetingTemplateGet201Response
   */
  template?: WorkspaceMeetingTemplateGet201ResponseTemplate
}

/**
 * Check if a given object implements the WorkspaceMeetingTemplateGet201Response interface.
 */
export function instanceOfWorkspaceMeetingTemplateGet201Response(
  value: object,
): boolean {
  let isInstance = true

  return isInstance
}

export function WorkspaceMeetingTemplateGet201ResponseFromJSON(
  json: any,
): WorkspaceMeetingTemplateGet201Response {
  return WorkspaceMeetingTemplateGet201ResponseFromJSONTyped(json, false)
}

export function WorkspaceMeetingTemplateGet201ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WorkspaceMeetingTemplateGet201Response {
  if (json === undefined || json === null) {
    return json
  }
  return {
    template: !exists(json, "template")
      ? undefined
      : WorkspaceMeetingTemplateGet201ResponseTemplateFromJSON(
          json["template"],
        ),
  }
}

export function WorkspaceMeetingTemplateGet201ResponseToJSON(
  value?: WorkspaceMeetingTemplateGet201Response | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    template: WorkspaceMeetingTemplateGet201ResponseTemplateToJSON(
      value.template,
    ),
  }
}
