/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
/**
 *
 * @export
 * @interface WorkspaceMeetingTemplateIdDelete200Response1Template
 */
export interface WorkspaceMeetingTemplateIdDelete200Response1Template {
  /**
   *
   * @type {string}
   * @memberof WorkspaceMeetingTemplateIdDelete200Response1Template
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof WorkspaceMeetingTemplateIdDelete200Response1Template
   */
  title?: string
  /**
   *
   * @type {string}
   * @memberof WorkspaceMeetingTemplateIdDelete200Response1Template
   */
  content?: string
  /**
   *
   * @type {Date}
   * @memberof WorkspaceMeetingTemplateIdDelete200Response1Template
   */
  updatedAt?: Date
}

/**
 * Check if a given object implements the WorkspaceMeetingTemplateIdDelete200Response1Template interface.
 */
export function instanceOfWorkspaceMeetingTemplateIdDelete200Response1Template(
  value: object,
): boolean {
  let isInstance = true

  return isInstance
}

export function WorkspaceMeetingTemplateIdDelete200Response1TemplateFromJSON(
  json: any,
): WorkspaceMeetingTemplateIdDelete200Response1Template {
  return WorkspaceMeetingTemplateIdDelete200Response1TemplateFromJSONTyped(
    json,
    false,
  )
}

export function WorkspaceMeetingTemplateIdDelete200Response1TemplateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WorkspaceMeetingTemplateIdDelete200Response1Template {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    title: !exists(json, "title") ? undefined : json["title"],
    content: !exists(json, "content") ? undefined : json["content"],
    updatedAt: !exists(json, "updatedAt")
      ? undefined
      : new Date(json["updatedAt"]),
  }
}

export function WorkspaceMeetingTemplateIdDelete200Response1TemplateToJSON(
  value?: WorkspaceMeetingTemplateIdDelete200Response1Template | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id,
    title: value.title,
    content: value.content,
    updatedAt:
      value.updatedAt === undefined ? undefined : value.updatedAt.toISOString(),
  }
}
