/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
import type { WorkspaceCalendarAvailableSlotsGet200ResponseSlotsInner } from "./WorkspaceCalendarAvailableSlotsGet200ResponseSlotsInner"
import {
  WorkspaceCalendarAvailableSlotsGet200ResponseSlotsInnerFromJSON,
  WorkspaceCalendarAvailableSlotsGet200ResponseSlotsInnerFromJSONTyped,
  WorkspaceCalendarAvailableSlotsGet200ResponseSlotsInnerToJSON,
} from "./WorkspaceCalendarAvailableSlotsGet200ResponseSlotsInner"

/**
 *
 * @export
 * @interface WorkspaceCalendarAvailableSlotsGet200Response
 */
export interface WorkspaceCalendarAvailableSlotsGet200Response {
  /**
   *
   * @type {Array<WorkspaceCalendarAvailableSlotsGet200ResponseSlotsInner>}
   * @memberof WorkspaceCalendarAvailableSlotsGet200Response
   */
  slots?: Array<WorkspaceCalendarAvailableSlotsGet200ResponseSlotsInner>
}

/**
 * Check if a given object implements the WorkspaceCalendarAvailableSlotsGet200Response interface.
 */
export function instanceOfWorkspaceCalendarAvailableSlotsGet200Response(
  value: object,
): boolean {
  let isInstance = true

  return isInstance
}

export function WorkspaceCalendarAvailableSlotsGet200ResponseFromJSON(
  json: any,
): WorkspaceCalendarAvailableSlotsGet200Response {
  return WorkspaceCalendarAvailableSlotsGet200ResponseFromJSONTyped(json, false)
}

export function WorkspaceCalendarAvailableSlotsGet200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WorkspaceCalendarAvailableSlotsGet200Response {
  if (json === undefined || json === null) {
    return json
  }
  return {
    slots: !exists(json, "slots")
      ? undefined
      : (json["slots"] as Array<any>).map(
          WorkspaceCalendarAvailableSlotsGet200ResponseSlotsInnerFromJSON,
        ),
  }
}

export function WorkspaceCalendarAvailableSlotsGet200ResponseToJSON(
  value?: WorkspaceCalendarAvailableSlotsGet200Response | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    slots:
      value.slots === undefined
        ? undefined
        : (value.slots as Array<any>).map(
            WorkspaceCalendarAvailableSlotsGet200ResponseSlotsInnerToJSON,
          ),
  }
}
