/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
/**
 *
 * @export
 * @interface WorkspaceCalendarIntegrationsGet200ResponseIntegrationsInner
 */
export interface WorkspaceCalendarIntegrationsGet200ResponseIntegrationsInner {
  /**
   *
   * @type {string}
   * @memberof WorkspaceCalendarIntegrationsGet200ResponseIntegrationsInner
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof WorkspaceCalendarIntegrationsGet200ResponseIntegrationsInner
   */
  provider?: string
  /**
   *
   * @type {string}
   * @memberof WorkspaceCalendarIntegrationsGet200ResponseIntegrationsInner
   */
  profileId?: string
  /**
   *
   * @type {string}
   * @memberof WorkspaceCalendarIntegrationsGet200ResponseIntegrationsInner
   */
  calendarId?: string | null
  /**
   *
   * @type {boolean}
   * @memberof WorkspaceCalendarIntegrationsGet200ResponseIntegrationsInner
   */
  syncEnabled?: boolean
  /**
   *
   * @type {Date}
   * @memberof WorkspaceCalendarIntegrationsGet200ResponseIntegrationsInner
   */
  lastSyncedAt?: Date | null
}

/**
 * Check if a given object implements the WorkspaceCalendarIntegrationsGet200ResponseIntegrationsInner interface.
 */
export function instanceOfWorkspaceCalendarIntegrationsGet200ResponseIntegrationsInner(
  value: object,
): boolean {
  let isInstance = true

  return isInstance
}

export function WorkspaceCalendarIntegrationsGet200ResponseIntegrationsInnerFromJSON(
  json: any,
): WorkspaceCalendarIntegrationsGet200ResponseIntegrationsInner {
  return WorkspaceCalendarIntegrationsGet200ResponseIntegrationsInnerFromJSONTyped(
    json,
    false,
  )
}

export function WorkspaceCalendarIntegrationsGet200ResponseIntegrationsInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WorkspaceCalendarIntegrationsGet200ResponseIntegrationsInner {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    provider: !exists(json, "provider") ? undefined : json["provider"],
    profileId: !exists(json, "profileId") ? undefined : json["profileId"],
    calendarId: !exists(json, "calendarId") ? undefined : json["calendarId"],
    syncEnabled: !exists(json, "syncEnabled") ? undefined : json["syncEnabled"],
    lastSyncedAt: !exists(json, "lastSyncedAt")
      ? undefined
      : json["lastSyncedAt"] === null
        ? null
        : new Date(json["lastSyncedAt"]),
  }
}

export function WorkspaceCalendarIntegrationsGet200ResponseIntegrationsInnerToJSON(
  value?: WorkspaceCalendarIntegrationsGet200ResponseIntegrationsInner | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id,
    provider: value.provider,
    profileId: value.profileId,
    calendarId: value.calendarId,
    syncEnabled: value.syncEnabled,
    lastSyncedAt:
      value.lastSyncedAt === undefined
        ? undefined
        : value.lastSyncedAt === null
          ? null
          : value.lastSyncedAt.toISOString(),
  }
}
