/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
/**
 *
 * @export
 * @interface WorkspaceCalendarAvailableSlotsGet200ResponseSlotsInner
 */
export interface WorkspaceCalendarAvailableSlotsGet200ResponseSlotsInner {
  /**
   *
   * @type {Date}
   * @memberof WorkspaceCalendarAvailableSlotsGet200ResponseSlotsInner
   */
  startTime?: Date
  /**
   *
   * @type {Date}
   * @memberof WorkspaceCalendarAvailableSlotsGet200ResponseSlotsInner
   */
  endTime?: Date
}

/**
 * Check if a given object implements the WorkspaceCalendarAvailableSlotsGet200ResponseSlotsInner interface.
 */
export function instanceOfWorkspaceCalendarAvailableSlotsGet200ResponseSlotsInner(
  value: object,
): boolean {
  let isInstance = true

  return isInstance
}

export function WorkspaceCalendarAvailableSlotsGet200ResponseSlotsInnerFromJSON(
  json: any,
): WorkspaceCalendarAvailableSlotsGet200ResponseSlotsInner {
  return WorkspaceCalendarAvailableSlotsGet200ResponseSlotsInnerFromJSONTyped(
    json,
    false,
  )
}

export function WorkspaceCalendarAvailableSlotsGet200ResponseSlotsInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WorkspaceCalendarAvailableSlotsGet200ResponseSlotsInner {
  if (json === undefined || json === null) {
    return json
  }
  return {
    startTime: !exists(json, "startTime")
      ? undefined
      : new Date(json["startTime"]),
    endTime: !exists(json, "endTime") ? undefined : new Date(json["endTime"]),
  }
}

export function WorkspaceCalendarAvailableSlotsGet200ResponseSlotsInnerToJSON(
  value?: WorkspaceCalendarAvailableSlotsGet200ResponseSlotsInner | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    startTime:
      value.startTime === undefined ? undefined : value.startTime.toISOString(),
    endTime:
      value.endTime === undefined ? undefined : value.endTime.toISOString(),
  }
}
