/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime"
/**
 *
 * @export
 * @interface WorkspaceCalendarIntegrationsIdDeleteRequest
 */
export interface WorkspaceCalendarIntegrationsIdDeleteRequest {
  /**
   *
   * @type {string}
   * @memberof WorkspaceCalendarIntegrationsIdDeleteRequest
   */
  calendarId?: string | null
  /**
   *
   * @type {boolean}
   * @memberof WorkspaceCalendarIntegrationsIdDeleteRequest
   */
  syncEnabled?: boolean | null
}

/**
 * Check if a given object implements the WorkspaceCalendarIntegrationsIdDeleteRequest interface.
 */
export function instanceOfWorkspaceCalendarIntegrationsIdDeleteRequest(
  value: object,
): boolean {
  let isInstance = true

  return isInstance
}

export function WorkspaceCalendarIntegrationsIdDeleteRequestFromJSON(
  json: any,
): WorkspaceCalendarIntegrationsIdDeleteRequest {
  return WorkspaceCalendarIntegrationsIdDeleteRequestFromJSONTyped(json, false)
}

export function WorkspaceCalendarIntegrationsIdDeleteRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WorkspaceCalendarIntegrationsIdDeleteRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    calendarId: !exists(json, "calendarId") ? undefined : json["calendarId"],
    syncEnabled: !exists(json, "syncEnabled") ? undefined : json["syncEnabled"],
  }
}

export function WorkspaceCalendarIntegrationsIdDeleteRequestToJSON(
  value?: WorkspaceCalendarIntegrationsIdDeleteRequest | null,
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    calendarId: value.calendarId,
    syncEnabled: value.syncEnabled,
  }
}
