/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateSavedItemRequest,
  GetSavedItems200ResponseInner,
  UpdateSavedItemRequest,
} from '../models';
import {
    CreateSavedItemRequestFromJSON,
    CreateSavedItemRequestToJSON,
    GetSavedItems200ResponseInnerFromJSON,
    GetSavedItems200ResponseInnerToJSON,
    UpdateSavedItemRequestFromJSON,
    UpdateSavedItemRequestToJSON,
} from '../models';

export interface CreateSavedItemOperationRequest {
    createSavedItemRequest: CreateSavedItemRequest;
}

export interface DeleteSavedItemRequest {
    id: string;
}

export interface GetSavedItemsRequest {
    folderId?: string;
    entityType?: string;
}

export interface UpdateSavedItemOperationRequest {
    id: string;
    updateSavedItemRequest?: UpdateSavedItemRequest;
}

/**
 * SavedApi - interface
 * 
 * @export
 * @interface SavedApiInterface
 */
export interface SavedApiInterface {
    /**
     * Save an entity for the current user
     * @param {CreateSavedItemRequest} createSavedItemRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SavedApiInterface
     */
    createSavedItemRaw(requestParameters: CreateSavedItemOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetSavedItems200ResponseInner>>;

    /**
     * Save an entity for the current user
     */
    createSavedItem(requestParameters: CreateSavedItemOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetSavedItems200ResponseInner>;

    /**
     * Delete a saved item by id
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SavedApiInterface
     */
    deleteSavedItemRaw(requestParameters: DeleteSavedItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Delete a saved item by id
     */
    deleteSavedItem(requestParameters: DeleteSavedItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Get saved items for the current workspace and user
     * @param {string} [folderId] Filter saved items by folder ID
     * @param {string} [entityType] Filter saved items by entity type
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SavedApiInterface
     */
    getSavedItemsRaw(requestParameters: GetSavedItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetSavedItems200ResponseInner>>>;

    /**
     * Get saved items for the current workspace and user
     */
    getSavedItems(requestParameters: GetSavedItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetSavedItems200ResponseInner>>;

    /**
     * Update a saved item by id
     * @param {string} id 
     * @param {UpdateSavedItemRequest} [updateSavedItemRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SavedApiInterface
     */
    updateSavedItemRaw(requestParameters: UpdateSavedItemOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetSavedItems200ResponseInner>>;

    /**
     * Update a saved item by id
     */
    updateSavedItem(requestParameters: UpdateSavedItemOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetSavedItems200ResponseInner>;

}

/**
 * 
 */
export class SavedApi extends runtime.BaseAPI implements SavedApiInterface {

    /**
     * Save an entity for the current user
     */
    async createSavedItemRaw(requestParameters: CreateSavedItemOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetSavedItems200ResponseInner>> {
        if (requestParameters.createSavedItemRequest === null || requestParameters.createSavedItemRequest === undefined) {
            throw new runtime.RequiredError('createSavedItemRequest','Required parameter requestParameters.createSavedItemRequest was null or undefined when calling createSavedItem.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/workspace/saved/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSavedItemRequestToJSON(requestParameters.createSavedItemRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetSavedItems200ResponseInnerFromJSON(jsonValue));
    }

    /**
     * Save an entity for the current user
     */
    async createSavedItem(requestParameters: CreateSavedItemOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetSavedItems200ResponseInner> {
        const response = await this.createSavedItemRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a saved item by id
     */
    async deleteSavedItemRaw(requestParameters: DeleteSavedItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deleteSavedItem.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/workspace/saved/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a saved item by id
     */
    async deleteSavedItem(requestParameters: DeleteSavedItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteSavedItemRaw(requestParameters, initOverrides);
    }

    /**
     * Get saved items for the current workspace and user
     */
    async getSavedItemsRaw(requestParameters: GetSavedItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetSavedItems200ResponseInner>>> {
        const queryParameters: any = {};

        if (requestParameters.folderId !== undefined) {
            queryParameters['folderId'] = requestParameters.folderId;
        }

        if (requestParameters.entityType !== undefined) {
            queryParameters['entityType'] = requestParameters.entityType;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/workspace/saved/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetSavedItems200ResponseInnerFromJSON));
    }

    /**
     * Get saved items for the current workspace and user
     */
    async getSavedItems(requestParameters: GetSavedItemsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetSavedItems200ResponseInner>> {
        const response = await this.getSavedItemsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a saved item by id
     */
    async updateSavedItemRaw(requestParameters: UpdateSavedItemOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetSavedItems200ResponseInner>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling updateSavedItem.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/workspace/saved/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateSavedItemRequestToJSON(requestParameters.updateSavedItemRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetSavedItems200ResponseInnerFromJSON(jsonValue));
    }

    /**
     * Update a saved item by id
     */
    async updateSavedItem(requestParameters: UpdateSavedItemOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetSavedItems200ResponseInner> {
        const response = await this.updateSavedItemRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
