/* tslint:disable */
/* eslint-disable */
/**
 * @fastify/swagger
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 8.15.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
  WorkspaceIntegrationsSettingsSettingsPatchRequest,
  WorkspaceMeetingTemplateIdDelete200Response,
} from "../models"
import {
  WorkspaceIntegrationsSettingsSettingsPatchRequestFromJSON,
  WorkspaceIntegrationsSettingsSettingsPatchRequestToJSON,
  WorkspaceMeetingTemplateIdDelete200ResponseFromJSON,
  WorkspaceMeetingTemplateIdDelete200ResponseToJSON,
} from "../models"
import * as runtime from "../runtime"

export interface WorkspaceIntegrationsSettingsSettingsPatchOperationRequest {
  workspaceIntegrationsSettingsSettingsPatchRequest: WorkspaceIntegrationsSettingsSettingsPatchRequest
}

/**
 * VideoConferenceApi - interface
 *
 * @export
 * @interface VideoConferenceApiInterface
 */
export interface VideoConferenceApiInterface {
  /**
   * Update video conference settings for the workspace
   * @param {WorkspaceIntegrationsSettingsSettingsPatchRequest} workspaceIntegrationsSettingsSettingsPatchRequest
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof VideoConferenceApiInterface
   */
  workspaceIntegrationsSettingsSettingsPatchRaw(
    requestParameters: WorkspaceIntegrationsSettingsSettingsPatchOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<WorkspaceMeetingTemplateIdDelete200Response>>

  /**
   * Update video conference settings for the workspace
   */
  workspaceIntegrationsSettingsSettingsPatch(
    requestParameters: WorkspaceIntegrationsSettingsSettingsPatchOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<WorkspaceMeetingTemplateIdDelete200Response>
}

/**
 *
 */
export class VideoConferenceApi
  extends runtime.BaseAPI
  implements VideoConferenceApiInterface
{
  /**
   * Update video conference settings for the workspace
   */
  async workspaceIntegrationsSettingsSettingsPatchRaw(
    requestParameters: WorkspaceIntegrationsSettingsSettingsPatchOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<WorkspaceMeetingTemplateIdDelete200Response>> {
    if (
      requestParameters.workspaceIntegrationsSettingsSettingsPatchRequest ===
        null ||
      requestParameters.workspaceIntegrationsSettingsSettingsPatchRequest ===
        undefined
    ) {
      throw new runtime.RequiredError(
        "workspaceIntegrationsSettingsSettingsPatchRequest",
        "Required parameter requestParameters.workspaceIntegrationsSettingsSettingsPatchRequest was null or undefined when calling workspaceIntegrationsSettingsSettingsPatch.",
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters["Content-Type"] = "application/json"

    const response = await this.request(
      {
        path: `/workspace/integrations/settings/settings`,
        method: "PATCH",
        headers: headerParameters,
        query: queryParameters,
        body: WorkspaceIntegrationsSettingsSettingsPatchRequestToJSON(
          requestParameters.workspaceIntegrationsSettingsSettingsPatchRequest,
        ),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      WorkspaceMeetingTemplateIdDelete200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * Update video conference settings for the workspace
   */
  async workspaceIntegrationsSettingsSettingsPatch(
    requestParameters: WorkspaceIntegrationsSettingsSettingsPatchOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<WorkspaceMeetingTemplateIdDelete200Response> {
    const response = await this.workspaceIntegrationsSettingsSettingsPatchRaw(
      requestParameters,
      initOverrides,
    )
    return await response.value()
  }
}
